/**
 * @yaks/id — entity ids for a yaks graph: the eid a client generates, and the
 * human id a person types.
 *
 * ## Two ids, one entity
 * An entity's durable identity is its **eid** — a UUID, generated by whoever
 * creates the entity, clients included, so a write never waits for the store to
 * assign an id. A UUID is not something a person can read or type, so an entity
 * also has a **human id**: a letter and a number, `B-7`. The number comes from
 * the store; the letter comes from the vocabulary.
 *
 * ## The `prefix` keyword
 * This package owns one keyword. A component that declares
 * `"prefix": "B"` numbers its entities in the `B` series:
 *
 * ```json
 * { "$defs": { "book": { "type": "object", "prefix": "B", "properties": {} } } }
 * ```
 *
 * Register it when you load the vocabulary and the ids follow:
 *
 * ```ts
 * import { loadVocab } from '@yaks/vocab'
 * import { idKeywords, idOf, mint, parse } from '@yaks/id'
 *
 * let v = loadVocab([catalog], [idKeywords])
 * let id = idOf(v)
 *
 * id({ eid: mint(), kind: 'book', num: 7 }) // 'B-7'
 * id({ eid: 'a3f19c02-4b00-4000-8000-000000000001', kind: 'book' }) // 'B#a3f19c024b'
 * parse('B-7') // { prefix: 'B', num: 7 }
 * parse('7') // { prefix: '', num: 7 } — the number is the identity
 * ```
 *
 * The letter is for display, the number is the identity: `B-7` and `7` name the
 * same book, so an id typed from memory still resolves. A component that
 * declares no prefix uses its own initial, so every entity has an id to show.
 *
 * The pieces:
 * - `keywords.ts` — the `prefix` keyword vocabulary, ready to register
 * - `mint.ts` — generating an eid, and the short handle an entity gets before
 *   it has been numbered
 * - `id.ts` — the prefix table, and `(prefix, num)` → id and back
 *
 * @module
 */

export * from './keywords.ts'
export * from './mint.ts'
export * from './id.ts'
