// The deployed page cannot import unpublished workspace exports. One browser
// bundle keeps its client, drafts, completion UI and signals in the same realm.
// Run from the checkout root before staging the app's files.
let root = new URL('../../', import.meta.url)
let bundle = await new Deno.Command(Deno.execPath(), {
  cwd: root,
  args: [
    'bundle',
    '--platform',
    'browser',
    'apps/vale/slash-runtime.ts',
    '-o',
    'apps/vale/slash-runtime.bundle.js',
  ],
}).spawn().status
if (!bundle.success) Deno.exit(bundle.code)
await Deno.copyFile(
  new URL('packages/ui/Choices.css', root),
  new URL('apps/vale/ui/Choices.css', root),
)

// Thin doors share the bundle's one Preact/client realm; workspace imports
// remain typed while the uploaded app never depends on unpublished exports.
let bridges = [
  ['ui-runtime.js', 'UI', await import('@yaks/ui')],
  ['ux-runtime.js', 'UX', await import('@yaks/ux')],
  ['ux-facet.js', 'UXFacet', await import('@yaks/ux/ui')],
  ['hooks-runtime.js', 'Hooks', await import('preact/hooks')],
  ['graph-runtime.js', 'Graph', await import('@yaks/graph')],
  ['query-runtime.js', 'Query', await import('@yaks/query')],
  ['guide-runtime.js', 'Guide', await import('../../packages/ui/guide.ts')],
] as const
for (let [file, namespace, exports] of bridges) {
  let names = Object.keys(exports).filter((name) => name != 'default')
  await Deno.writeTextFile(
    new URL(`apps/vale/${file}`, root),
    `// Generated by build-slash.ts; do not edit.\nimport { ${namespace} } from './slash-runtime.bundle.js'\nexport const { ${
      names.join(', ')
    } } = ${namespace}\n`,
  )
}
// import.meta.url in the bundle is the bundle's URL. Carry each stylesheet
// at the same relative address its source declares, never a second CSS source.
for await (let file of Deno.readDir(new URL('packages/ui/', root))) {
  if (file.isFile && file.name.endsWith('.css')) {
    await Deno.copyFile(
      new URL(`packages/ui/${file.name}`, root),
      new URL(`apps/vale/${file.name}`, root),
    )
  }
}
await Deno.mkdir(new URL('apps/vale/ledger/', root), { recursive: true })
for await (let file of Deno.readDir(new URL('packages/ui/ledger/', root))) {
  if (file.isFile && file.name.endsWith('.css')) {
    await Deno.copyFile(
      new URL(`packages/ui/ledger/${file.name}`, root),
      new URL(`apps/vale/ledger/${file.name}`, root),
    )
  }
}

// Push consumes a directory as the complete desired release. Prepare one
// containing the generated runtime too, rather than a tracked-file-only tree
// which would delete the browser's dependency bundle from the next release.
let stage = Deno.args[0]
if (stage) {
  let target = new URL(`${stage.replace(/\/$/, '')}/`, `file://${Deno.cwd()}/`)
  let source = new URL('./', import.meta.url)
  if (target.href.startsWith(source.href)) {
    throw new Error(
      'Stage outside apps/vale so the copy cannot include itself.',
    )
  }
  await Deno.mkdir(target, { recursive: true })
  let copy = async (dir: URL, rel = '') => {
    for await (let entry of Deno.readDir(dir)) {
      if (entry.name.startsWith('.') || entry.name == 'node_modules') continue
      let path = rel + entry.name
      if (entry.isDirectory) {
        await Deno.mkdir(new URL(`${path}/`, target), { recursive: true })
        await copy(new URL(`${entry.name}/`, dir), `${path}/`)
      } else if (
        entry.isFile && !/_test\.ts$|_fixture\.ts$|\.md$/.test(path) &&
        !['build-slash.ts', 'slash-runtime.ts'].includes(path)
      ) {
        await Deno.copyFile(new URL(entry.name, dir), new URL(path, target))
      }
    }
  }
  await copy(source)
  console.log(`Prepared Vale runtime files in ${target.pathname}`)
}
