// The fire, furthest south-west: Emberfall's forges under a falling of
// embers, the black reach of Cinderreach, grey Ashkeep and its last knight,
// and the Maw at the end of the world.
import type { Row } from '../levels.ts'

export let FIRE: Record<string, Row> = {
  emberfall: {
    name: 'Emberfall',
    seed: 167,
    cell: [-3, 3],
    arrive: 'forge',
    places: {
      ash: { kind: 'emberash', at: [128, 128] },
      volcano: { kind: 'lavafall', at: [160, 98] },
      moor: { kind: 'cinderheath', at: [94, 104] },
      forge: { kind: 'forgetown', at: [122, 134] },
      northwest: { kind: 'emberash', at: [50, 46] },
      northeast: { kind: 'cinderheath', at: [210, 51] },
      southwest: { kind: 'volcano', at: [51, 209] },
      southeast: { kind: 'emberash', at: [211, 214] },
    },
    roads: {
      east: 'giantsteps',
      west: 'cinderreach',
    },
    wild: 'emberash',
    look: {
      ground: {
        ash: 0x5a4a44,
        heath: 0x3a2e2e,
        dry: 0x6a5a4a,
        grass: 0x6a6a44,
        snow: 0x6a5a54,
        path: 0x8a6a50,
      },
      water: [0x2a1a14, 0x4a2a1a, 0xc8703a],
      sky: 0xd88050,
      tint: 0.45,
      haze: 1.5,
      air: 'embers',
    },
  },
  cinderreach: {
    name: 'Cinderreach',
    seed: 173,
    cell: [-4, 3],
    arrive: 'ash',
    places: {
      ash: { kind: 'cinderflats', at: [128, 128] },
      volcano: { kind: 'volcano', at: [102, 102] },
      cone: { kind: 'vents', at: [160, 156] },
      northwest: { kind: 'cinderflats', at: [43, 51] },
      northeast: { kind: 'volcano', at: [216, 43] },
      southwest: { kind: 'vents', at: [44, 214] },
      southeast: { kind: 'cinderflats', at: [217, 206] },
    },
    roads: {
      north: 'tombsands',
      east: 'emberfall',
      south: 'ashkeep',
      west: 'maw',
    },
    wild: 'cinderflats',
    look: {
      ground: {
        ash: 0x2e2c2a,
        stone: 0x44403c,
        clay: 0xc8b040,
        snow: 0x3a3634,
        path: 0x5a524a,
      },
      sky: 0x6a625e,
      tint: 0.55,
      haze: 1.9,
      air: 'ash',
    },
  },
  ashkeep: {
    name: 'Ashkeep',
    seed: 179,
    cell: [-4, 4],
    arrive: 'keep',
    places: {
      ash: { kind: 'ashfield', at: [128, 128] },
      keep: { kind: 'keep', at: [128, 118] },
      gate: { kind: 'ashgate', at: [154, 152] },
      volcano: { kind: 'coldcone', at: [100, 154] },
      northwest: { kind: 'ashfield', at: [49, 43] },
      northeast: { kind: 'coldcone', at: [209, 48] },
      southwest: { kind: 'volcano', at: [50, 206] },
      southeast: { kind: 'ashfield', at: [210, 211] },
    },
    roads: {
      north: 'cinderreach',
    },
    wild: 'ashfield',
    look: {
      ground: {
        ash: 0x707070,
        stone: 0x5a5a5e,
        snow: 0x8a8a8e,
        path: 0x8a8278,
      },
      sky: 0x8a8a92,
      tint: 0.5,
      haze: 1.4,
    },
  },
  maw: {
    name: 'The Maw',
    seed: 181,
    cell: [-5, 3],
    arrive: 'ash',
    places: {
      ash: { kind: 'scorch', at: [128, 134] },
      maw: { kind: 'maw', at: [128, 114] },
      cone: { kind: 'spatter', at: [94, 152] },
      northwest: { kind: 'scorch', at: [51, 49] },
      northeast: { kind: 'spatter', at: [211, 41] },
      southwest: { kind: 'volcano', at: [39, 212] },
      southeast: { kind: 'scorch', at: [212, 217] },
    },
    roads: {
      east: 'cinderreach',
    },
    wild: 'scorch',
    look: {
      ground: {
        ash: 0x3a3232,
        stone: 0x4a3e3e,
        ember: 0xff5a1a,
        snow: 0x3a2e2e,
        path: 0x6a5448,
      },
      water: [0x3a0a04, 0x6a1a08, 0xff8a3a],
      sky: 0x6a1a10,
      tint: 0.65,
      haze: 2.2,
      air: 'sparks',
    },
  },
}
