// The sands, south-west past the coast: Dustmere's dust where a mere dried,
// Palmwell's green water and caravans, the white glare of the Sunscar Dunes,
// Redmesa's red rock, and the tombs of Tombsands at dusk.
import type { Row } from '../levels.ts'

export let SANDS: Record<string, Row> = {
  dustmere: {
    name: 'Dustmere',
    seed: 109,
    cell: [-3, 1],
    arrive: 'well',
    places: {
      dunes: { kind: 'dustpan', at: [128, 128] },
      mesa: { kind: 'oldshore', at: [160, 100] },
      oasis: { kind: 'lastpool', at: [154, 152] },
      well: { kind: 'welltown', at: [122, 126] },
      northwest: { kind: 'dunes', at: [44, 41] },
      northeast: { kind: 'oldshore', at: [217, 46] },
      southwest: { kind: 'dunes', at: [45, 217] },
      southeast: { kind: 'lastpool', at: [205, 209] },
    },
    roads: {
      north: 'driftwood',
      south: 'sunscar',
      west: 'palmwell',
    },
    wild: 'dustpan',
    look: {
      ground: {
        dry: 0xd4c4a0,
        mud: 0x9a8868,
        sand: 0xd8c8a4,
        stone: 0xb8ab94,
        snow: 0xcfc2a4,
      },
      water: [0x4a3e2c, 0x6e5e44, 0xb0a080],
      sky: 0xd8c4a0,
      tint: 0.45,
      haze: 1.9,
      air: 'dust',
    },
  },
  palmwell: {
    name: 'Palmwell',
    seed: 113,
    cell: [-4, 1],
    arrive: 'camp',
    places: {
      dunes: { kind: 'golddunes', at: [128, 128] },
      oasis: { kind: 'palmgrove', at: [114, 116] },
      mesa: { kind: 'mesa', at: [160, 160] },
      camp: { kind: 'caravan', at: [136, 136] },
      northwest: { kind: 'golddunes', at: [48, 40] },
      northeast: { kind: 'mesa', at: [208, 45] },
      southwest: { kind: 'palmgrove', at: [49, 216] },
      southeast: { kind: 'golddunes', at: [209, 208] },
    },
    roads: {
      east: 'dustmere',
      south: 'redmesa',
    },
    wild: 'golddunes',
    look: {
      ground: {
        sand: 0xf2d690,
        lush: 0x3a9a44,
        grass: 0x6ab050,
        snow: 0xeedcb0,
      },
      water: [0x0a4a5a, 0x1a9aa8, 0xc8fff0],
      sky: 0xfff0c8,
      tint: 0.3,
    },
  },
  sunscar: {
    name: 'Sunscar Dunes',
    seed: 127,
    cell: [-3, 2],
    arrive: 'dunes',
    places: {
      dunes: { kind: 'greatdunes', at: [128, 128] },
      east: { kind: 'bonedunes', at: [158, 104] },
      buried: { kind: 'buried', at: [104, 104] },
      mesa: { kind: 'scar', at: [150, 154] },
      northwest: { kind: 'greatdunes', at: [49, 43] },
      northeast: { kind: 'scar', at: [209, 48] },
      southwest: { kind: 'greatdunes', at: [50, 206] },
      southeast: { kind: 'scar', at: [210, 211] },
    },
    roads: {
      north: 'dustmere',
      west: 'redmesa',
    },
    wild: 'greatdunes',
    look: {
      ground: {
        sand: 0xf4dc98,
        ash: 0x243432,
        stone: 0xd8c8a0,
        snow: 0xf8ecc8,
      },
      sky: 0xfff4d0,
      tint: 0.35,
      haze: 1.2,
      air: 'heat',
    },
  },
  redmesa: {
    name: 'Redmesa',
    seed: 131,
    cell: [-4, 2],
    arrive: 'mesa',
    places: {
      dunes: { kind: 'dunes', at: [128, 164] },
      mesa: { kind: 'redrock', at: [128, 128] },
      west: { kind: 'buttes', at: [100, 100] },
      east: { kind: 'buttes', at: [158, 156] },
      oasis: { kind: 'spring', at: [154, 104] },
      northwest: { kind: 'dunes', at: [40, 42] },
      northeast: { kind: 'buttes', at: [213, 47] },
      southwest: { kind: 'buttes', at: [41, 205] },
      southeast: { kind: 'dunes', at: [214, 210] },
    },
    roads: {
      north: 'palmwell',
      east: 'sunscar',
      west: 'tombsands',
    },
    wild: 'buttes',
    look: {
      ground: {
        sand: 0xd88a5a,
        clay: 0xb85a38,
        dry: 0xc8905a,
        grass: 0x9aa050,
        lush: 0x6a9040,
        stone: 0xa86a4a,
        snow: 0xc87850,
      },
      water: [0x2a4a4a, 0x4a7a6a, 0xb8d8c0],
      sky: 0xf0b088,
      tint: 0.4,
      haze: 1.2,
    },
  },
  tombsands: {
    name: 'Tombsands',
    seed: 137,
    cell: [-5, 2],
    arrive: 'tombs',
    places: {
      dunes: { kind: 'tombdunes', at: [128, 128] },
      tombs: { kind: 'necropolis', at: [128, 112] },
      sunken: { kind: 'sunkentomb', at: [102, 150] },
      mesa: { kind: 'tombcliffs', at: [160, 156] },
      northwest: { kind: 'tombdunes', at: [46, 47] },
      northeast: { kind: 'dunes', at: [206, 39] },
      southwest: { kind: 'dunes', at: [47, 210] },
      southeast: { kind: 'tombdunes', at: [207, 215] },
    },
    roads: {
      east: 'redmesa',
      south: 'cinderreach',
    },
    wild: 'tombdunes',
    look: {
      ground: {
        sand: 0xe8d0a0,
        stone: 0xd8c098,
        clay: 0xc8a878,
        snow: 0xe0c8a0,
      },
      sky: 0xe8a868,
      tint: 0.4,
      haze: 1.3,
    },
  },
}
