// The vale: Mossvale, where every hero starts, and the green country and
// the woods north of it.
import type { Row } from '../levels.ts'

export let VALE: Record<string, Row> = {
  mossvale: {
    name: 'Mossvale',
    seed: 0,
    cell: [0, 0],
    arrive: 'plaza',
    places: {
      crags: { kind: 'crags', at: [94, 162] },
      ridge: { kind: 'ridge', at: [166, 164] },
      woods: { kind: 'woods', at: [130, 89] },
      lake: { kind: 'lake', at: [90, 113] },
      fields: { kind: 'fields', at: [163, 116] },
      plaza: { kind: 'village', at: [128, 128] },
      northwest: { kind: 'woods', at: [39, 39] },
      northeast: { kind: 'crags', at: [212, 44] },
      southwest: { kind: 'meadow', at: [40, 215] },
      southeast: { kind: 'woods', at: [213, 207] },
    },
    roads: {
      north: 'fernwood',
      east: 'reedmarsh',
      south: 'stonestep',
      west: 'birchmere',
    },
    wild: 'meadow',
  },
  birchmere: {
    name: 'Birchmere',
    seed: 7,
    cell: [-1, 0],
    arrive: 'green',
    places: {
      mere: { kind: 'mere', at: [112, 139] },
      woods: { kind: 'birchwood', at: [149, 99] },
      east: { kind: 'birchwood', at: [162, 149] },
      fields: { kind: 'fields', at: [104, 99] },
      green: { kind: 'mereside', at: [133, 126] },
      northwest: { kind: 'birchwood', at: [46, 47] },
      northeast: { kind: 'meadow', at: [206, 39] },
      southwest: { kind: 'birchwood', at: [47, 210] },
      southeast: { kind: 'lake', at: [207, 215] },
    },
    roads: {
      north: 'clovermead',
      east: 'mossvale',
      west: 'gullwick',
    },
    wild: 'birchwood',
    look: {
      ground: { grass: 0x9ccf6e, lush: 0x7fbd5c },
      sky: 0xe8f4ff,
      tint: 0.15,
      air: 'fluff',
    },
  },
  clovermead: {
    name: 'Clovermead',
    seed: 11,
    cell: [-1, -1],
    arrive: 'meadow',
    places: {
      meadow: { kind: 'clover', at: [124, 126] },
      woods: { kind: 'woods', at: [98, 102] },
      pond: { kind: 'lake', at: [154, 150] },
      copse: { kind: 'woods', at: [162, 104] },
      northwest: { kind: 'meadow', at: [50, 46] },
      northeast: { kind: 'woods', at: [210, 51] },
      southwest: { kind: 'lake', at: [51, 209] },
      southeast: { kind: 'meadow', at: [211, 214] },
    },
    roads: {
      east: 'fernwood',
      south: 'birchmere',
    },
    wild: 'meadow',
    look: {
      ground: { grass: 0x86d468, lush: 0x6cc45a },
      sky: 0xfff0c8,
      tint: 0.12,
      air: 'pollen',
    },
  },
  fernwood: {
    name: 'Fernwood',
    seed: 13,
    cell: [0, -1],
    arrive: 'glade',
    places: {
      woods: { kind: 'fernwood', at: [104, 100] },
      deep: { kind: 'fernheart', at: [158, 106] },
      meadow: { kind: 'meadow', at: [100, 152] },
      pond: { kind: 'lake', at: [154, 154] },
      glade: { kind: 'fernhamlet', at: [126, 130] },
      northwest: { kind: 'fernwood', at: [39, 39] },
      northeast: { kind: 'meadow', at: [212, 44] },
      southwest: { kind: 'lake', at: [40, 215] },
      southeast: { kind: 'fernwood', at: [213, 207] },
    },
    roads: {
      north: 'elderglade',
      east: 'greypine',
      south: 'mossvale',
      west: 'clovermead',
    },
    wild: 'fernwood',
    look: {
      ground: { grass: 0x5c9e46, lush: 0x3f8a3c },
      sky: 0xa8d8a0,
      tint: 0.14,
      haze: 1.3,
    },
  },
  elderglade: {
    name: 'Elderglade',
    seed: 17,
    cell: [0, -2],
    arrive: 'heart',
    places: {
      heart: { kind: 'eldergrove', at: [128, 126] },
      west: { kind: 'elders', at: [98, 104] },
      east: { kind: 'elders', at: [158, 148] },
      pool: { kind: 'lake', at: [102, 154] },
      meadow: { kind: 'meadow', at: [156, 100] },
      northwest: { kind: 'elders', at: [43, 51] },
      northeast: { kind: 'meadow', at: [216, 43] },
      southwest: { kind: 'lake', at: [44, 214] },
      southeast: { kind: 'elders', at: [217, 206] },
    },
    roads: {
      south: 'fernwood',
      west: 'glowcap',
    },
    wild: 'elders',
    look: {
      ground: { grass: 0xa8c85a, lush: 0x86b04c },
      sky: 0xffd890,
      tint: 0.2,
      air: 'motes',
    },
  },
  greypine: {
    name: 'Greypine',
    seed: 19,
    cell: [1, -1],
    arrive: 'pines',
    places: {
      pines: { kind: 'greypines', at: [124, 122] },
      tarn: { kind: 'lake', at: [154, 148] },
      crags: { kind: 'watchcrag', at: [98, 156] },
      high: { kind: 'greypines', at: [160, 98] },
      northwest: { kind: 'greypines', at: [45, 44] },
      northeast: { kind: 'crags', at: [205, 49] },
      southwest: { kind: 'lake', at: [46, 207] },
      southeast: { kind: 'greypines', at: [206, 212] },
    },
    roads: {
      east: 'wolfden',
      west: 'fernwood',
    },
    wild: 'greypines',
    look: {
      ground: { grass: 0x8e9e80, lush: 0x6f8a6a, dry: 0xa0a08a },
      water: [0x4a6a78, 0x6a8a94, 0xc8d2d6],
      sky: 0xb8c0c4,
      tint: 0.4,
      haze: 2,
    },
  },
  wolfden: {
    name: 'Wolfden',
    seed: 23,
    cell: [2, -1],
    arrive: 'pines',
    places: {
      pines: { kind: 'hollow', at: [114, 114] },
      crags: { kind: 'lair', at: [156, 104] },
      scree: { kind: 'dens', at: [108, 160] },
      tarn: { kind: 'lake', at: [158, 154] },
      northwest: { kind: 'hollow', at: [49, 43] },
      northeast: { kind: 'dens', at: [209, 48] },
      southwest: { kind: 'lake', at: [50, 206] },
      southeast: { kind: 'dens', at: [210, 211] },
    },
    roads: {
      east: 'frostmoor',
      west: 'greypine',
    },
    wild: 'hollow',
    look: {
      ground: {
        grass: 0x4d6440,
        lush: 0x3c5434,
        dry: 0x6a6a50,
        stone: 0x6f6e68,
      },
      water: [0x1e2e34, 0x34464c, 0x8a98a0],
      sky: 0x4a5068,
      tint: 0.5,
      haze: 1.8,
    },
  },
}
