import './testing.ts'
import { assertEquals, assertThrows } from '@std/assert'
import { eidOf } from '@yaks/archetype'
import { archetypeTables } from './live_archetypes.ts'
import { applyLocal, config, landSub, useRoute } from './live.ts'
