// The people of home: Mossvale, where every hero starts and Elder Wren
// teaches them before sending them down the west road, and the gentle
// country round Birchmere and Clovermead.
import type { Giver, Quest } from '../quests.ts'

export let givers: Giver[] = [
  {
    id: 'wren',
    name: 'Elder Wren',
    level: 'mossvale',
    place: 'plaza',
    offset: [-1.5, -3],
    greets:
      'Four roads leave the vale, one to each edge of it: north to Fernwood, east to Reedmarsh, south to Stonestep and west to Birchmere. Every one of them has somebody on it who needs a hand.',
    look: { tint: '#4f7a4a', hair: '#e9e6df', skin: '#d9a98a' },
    staff: true,
  },
  {
    id: 'pip',
    name: 'Pip',
    level: 'mossvale',
    place: 'plaza',
    offset: [1, 5],
    greets: 'When I’m big I’m going to have a sword just like yours.',
    look: { tint: '#d9824a', hair: '#6b3f22', skin: '#f0c4a0' },
  },
  {
    id: 'alder',
    name: 'Reeve Alder',
    level: 'birchmere',
    place: 'green',
    offset: [-1.5, -3],
    greets:
      'Welcome to Birchmere. Any friend of Wren’s eats at my table, though she never writes.',
    look: { tint: '#6b5a8a', hair: '#cfcac0', skin: '#c9926e' },
    staff: true,
  },
  {
    id: 'sorrel',
    name: 'Sorrel the herbwife',
    level: 'birchmere',
    place: 'green',
    offset: [6.5, -1],
    greets: 'Mint for the head, moss for the heart, jelly for nearly anything.',
    look: { tint: '#7aa04a', hair: '#e0b05a', skin: '#f1c9a5' },
  },
  {
    id: 'mira',
    name: 'Mira of the mere',
    level: 'birchmere',
    place: 'mere',
    offset: [13, -8],
    greets: 'The mere is clear today. You can see all the way down.',
    look: { tint: '#4a8a9a', hair: '#1f1a18', skin: '#a86e4c' },
  },
  {
    id: 'fenn',
    name: 'Fenn the shepherd',
    level: 'birchmere',
    place: 'fields',
    offset: [11, 21.5],
    greets: 'The flock is grazing. That’s all a shepherd ever wants.',
    look: { tint: '#a07850', hair: '#e6e2da', skin: '#dca888' },
    staff: true,
  },
  {
    id: 'hazel',
    name: 'Hazel the woodcutter',
    level: 'birchmere',
    place: 'woods',
    offset: [-5, 19.5],
    greets: 'Mind the chips. They fly further than you think.',
    look: { tint: '#8a4a3a', hair: '#4a2e1c', skin: '#e2b08a' },
  },
  {
    id: 'mab',
    name: 'Mab the beekeeper',
    level: 'clovermead',
    place: 'meadow',
    offset: [-2, -4],
    greets: 'Hear that hum? That’s a happy hive. Mind where you step.',
    look: { tint: '#e0b33a', hair: '#8a8a82', skin: '#c98f6a' },
    staff: true,
  },
]

export let quests: Quest[] = [
  // Elder Wren, the spine of the story, by the Mossvale fire.
  {
    id: 'wren-jelly',
    giver: 'wren',
    goal: 'gather',
    target: 'jelly',
    count: 4,
    xp: 70,
    gift: 'tonic',
    title: 'Jelly for the kettle',
    body:
      'The moss slimes out in the meadow are fat with jelly this season. Bring me four and I will brew you a tonic that mends a bruise or two.',
  },
  {
    id: 'wren-boars',
    giver: 'wren',
    after: 'wren-jelly',
    goal: 'slay',
    target: 'boar',
    count: 4,
    xp: 140,
    gift: 'blade2',
    title: 'Bristles in the turnips',
    body:
      'Bristleboars are rooting up the edge of Whisperwood, north of here, and my turnips with it. Drive off four of them, and take my old blade, Boarsbane, for your trouble.',
  },
  {
    id: 'wren-crags',
    giver: 'wren',
    after: 'wren-boars',
    goal: 'slay',
    target: 'crag',
    count: 3,
    xp: 240,
    gift: 'blade3',
    title: 'The stones that walk',
    body:
      'Up in Craghollow, to the south-west, the rocks have started walking. Cragbacks, the old folk called them. Topple three, and this cleaver is yours. Then take the west road to Birchmere: Reeve Alder keeps an old book, and I want to know what it says about thorns.',
  },
  {
    id: 'wren-thornback',
    giver: 'wren',
    after: 'wren-crags',
    goal: 'slay',
    target: 'thornback',
    count: 1,
    xp: 600,
    gift: 'draught',
    title: 'Old Thornback',
    body:
      'Something old nests on Thornback Ridge, south-east of the village, and every beast in the vale is restless because of it. It is too much for you yet. Walk the roads, come back stronger, and bring friends.',
  },
  {
    id: 'wren-crown',
    giver: 'wren',
    after: 'wren-thornback',
    goal: 'gather',
    target: 'crown',
    count: 1,
    xp: 300,
    gift: 'draught',
    title: 'A crown of briar',
    body:
      'Old Thornback did not grow that crown. Somebody set it on him, and the Reeve’s book says who: the briar itself, crowning what it wakes. Give it here, and I will keep it where I can watch it.',
  },
  {
    id: 'wren-home',
    giver: 'wren',
    after: 'garrow-wyrm',
    level: 'maw',
    goal: 'gather',
    target: 'ember',
    count: 1,
    xp: 2000,
    gift: 'elixir',
    title: 'Fire for the hearth',
    body:
      'You went all the way to the Maw and came back. Every hearth in the vale was lit from the deep fire once, before the briar. Give me an ember from down there, and the plaza fire will burn clean again.',
  },
  // Pip, who wants to be you.
  {
    id: 'pip-slimes',
    giver: 'pip',
    goal: 'slay',
    target: 'slime',
    count: 5,
    xp: 70,
    title: 'The ball that got away',
    body:
      'A slime swallowed my ball, down past the last lamp. I don’t know which one. If you pop five, it has to be in one of them, right?',
  },
  {
    id: 'pip-feathers',
    giver: 'pip',
    after: 'pip-slimes',
    goal: 'gather',
    target: 'feather',
    count: 3,
    xp: 45,
    title: 'A hat for a hero',
    body:
      'No ball. Never mind. I’m making a hat now, a hero hat, with feathers in. The hens and ducks round the village drop the best ones. Three, please.',
  },
  // Reeve Alder, who keeps the old book in Birchmere.
  {
    id: 'alder-thorns',
    giver: 'alder',
    after: 'wren-crags',
    goal: 'slay',
    target: 'boar',
    count: 6,
    xp: 200,
    gift: 'tonic',
    title: 'The Reeve of Birchmere',
    body:
      'So Wren sent you. She writes that Mossvale’s beasts have thorns in them now, and so do ours: the boars in Emberwood, south-east of the green, have briar in their hides. Drive off six, and I’ll open the old book.',
  },
  {
    id: 'alder-tusks',
    giver: 'alder',
    after: 'alder-thorns',
    goal: 'gather',
    target: 'tusk',
    count: 5,
    xp: 260,
    title: 'Proof for the council',
    body:
      'The council laughs at thorns in a boar. It won’t laugh at five tusks on the table, thorns and all. Bring them, and we’ll see who laughs.',
  },
  {
    id: 'alder-ring',
    giver: 'alder',
    after: 'alder-tusks',
    level: 'mossvale',
    goal: 'gather',
    target: 'shard',
    count: 3,
    xp: 400,
    gift: 'tonic',
    title: 'The Greenkeepers’ ring',
    body:
      'The book says the Greenkeepers held the briar back with a ring of crag shards. There are no crags in Birchmere. Take the road back to Mossvale, climb into Craghollow, and bring me three.',
  },
  {
    id: 'alder-gates',
    giver: 'alder',
    after: 'alder-ring',
    goal: 'slay',
    target: 'goblin',
    count: 5,
    xp: 420,
    gift: 'draught',
    title: 'Four roads',
    body:
      'Bramble goblins came up the road last night with briar in their hair. The book says the Greenkeepers set a ward at the end of each road out of Mossvale: the Elder Heart up the north road, the bell of the Sunken Kirk down the east road, the old king’s barrow down the south road, and the light on Stormhead, out past Gullwick on our own west road. Drive off five goblins, then go and see if the wards still hold.',
  },
  // Sorrel the herbwife, by the well in Birchmere.
  {
    id: 'sorrel-jelly',
    giver: 'sorrel',
    goal: 'gather',
    target: 'jelly',
    count: 6,
    xp: 100,
    gift: 'tonic',
    title: 'Jelly and patience',
    body:
      'A tonic is mostly slime jelly and patience. I have the patience. Six jellies, and one of the tonics is yours.',
  },
  {
    id: 'sorrel-slimes',
    giver: 'sorrel',
    after: 'sorrel-jelly',
    goal: 'slay',
    target: 'slime',
    count: 10,
    xp: 140,
    title: 'In the herb beds',
    body:
      'The slimes have found my herb beds, and they don’t leave much. Ten of them, please, and step softly round the mint.',
  },
  {
    id: 'sorrel-tusks',
    giver: 'sorrel',
    after: 'sorrel-slimes',
    goal: 'gather',
    target: 'tusk',
    count: 2,
    xp: 100,
    gift: 'tonic',
    title: 'A poultice for the flock',
    body:
      'Fenn’s sheep keep getting gored. Boar tusk, ground fine, draws the swelling out. Two tusks, and take a tonic for the road.',
  },
  // Mira of the mere, on the shore of the Birchmere mere.
  {
    id: 'mira-slimes',
    giver: 'mira',
    after: 'mira-jelly',
    goal: 'slay',
    target: 'slime',
    count: 8,
    xp: 110,
    title: 'Clouded water',
    body:
      'Slimes slide into the mere to cool off and cloud it green for days. Clear eight of them off the shore, and the water will settle.',
  },
  {
    id: 'mira-jelly',
    giver: 'mira',
    goal: 'gather',
    target: 'jelly',
    count: 4,
    xp: 70,
    title: 'Lamps for the jetty',
    body:
      'Slime jelly glows a little in a jar after dark. Four jars along the jetty, and the boats find their way home.',
  },
  {
    id: 'mira-snakes',
    giver: 'mira',
    after: 'mira-slimes',
    goal: 'slay',
    target: 'watersnake',
    count: 2,
    xp: 210,
    gift: 'tonic',
    title: 'Something in the reeds',
    body:
      'A water snake has moved into the reeds by the jetty, then another. Two of them, and the children can paddle again.',
  },
  // Fenn the shepherd, in the north-west fields of Birchmere.
  {
    id: 'fenn-boars',
    giver: 'fenn',
    after: 'fenn-tusks',
    goal: 'slay',
    target: 'boar',
    count: 6,
    xp: 200,
    title: 'Sheep in a panic',
    body:
      'The boars come out of the Whitebirches, off to the east, and run my sheep ragged. They never used to. Six of them, and my flock might eat again.',
  },
  {
    id: 'fenn-tusks',
    giver: 'fenn',
    goal: 'gather',
    target: 'tusk',
    count: 3,
    xp: 160,
    gift: 'tonic',
    title: 'A fence of tusks',
    body:
      'An old trick: tusks set in the gatepost, points out. A boar smells its own kind and turns away. Three should do the gate.',
  },
  {
    id: 'fenn-adders',
    giver: 'fenn',
    after: 'fenn-boars',
    goal: 'slay',
    target: 'adder',
    count: 3,
    xp: 250,
    title: 'Adders in the grass',
    body:
      'Heath adders in the long grass now, and a bitten ewe is a lost ewe. Three of them, and I’ll sleep tonight.',
  },
  // Hazel the woodcutter, below the Whitebirches.
  {
    id: 'hazel-boars',
    giver: 'hazel',
    goal: 'slay',
    target: 'boar',
    count: 8,
    xp: 270,
    title: 'Axes down',
    body:
      'We can’t fell a birch without a Bristleboar coming at us out of the bracken. Eight of them, and we’ll get back to work.',
  },
  {
    id: 'hazel-hornets',
    giver: 'hazel',
    after: 'hazel-boars',
    goal: 'slay',
    target: 'hornet',
    count: 4,
    xp: 240,
    gift: 'tonic',
    title: 'A nest in the birches',
    body:
      'Now the hornets. They’ve built a nest the size of a barrel in the Whitebirches, and they don’t like axes. Four of them, and I’ll smoke out the rest.',
  },
  // Mab the beekeeper, in the middle of Clovermead.
  {
    id: 'mab-glimmers',
    giver: 'mab',
    goal: 'slay',
    target: 'glimmer',
    count: 4,
    xp: 420,
    title: 'Lights in the clover',
    body:
      'Glimmer wisps drift over the meadow at dusk, and the bees follow them away and never come home. Four of them, and my hives stay full.',
  },
  {
    id: 'mab-spiders',
    giver: 'mab',
    after: 'mab-glimmers',
    goal: 'slay',
    target: 'spider',
    count: 6,
    xp: 270,
    title: 'Webs on the hives',
    body:
      'Wood spiders are coming out of the trees north-west of here and webbing up my hives. Six of them, and the bees can fly again.',
  },
  {
    id: 'mab-bear',
    giver: 'mab',
    after: 'mab-spiders',
    goal: 'slay',
    target: 'bear',
    count: 1,
    xp: 180,
    gift: 'tonic',
    title: 'A bear with a sweet tooth',
    body:
      'A brown bear has found the hives, and a bear that has found honey never forgets the way. Send it back to the woods for good.',
  },
  {
    id: 'mab-warchief',
    giver: 'mab',
    after: 'mab-bear',
    goal: 'slay',
    target: 'warchief',
    count: 1,
    xp: 340,
    gift: 'draught',
    title: 'The goblin who wants my honey',
    body:
      'A goblin warchief has been through the meadow twice, sizing up my hives, with briar in his helmet. He’ll be back with his friends. Get to him first.',
  },
]
