// The people of the west road, out past Birchmere: the harbour of
// Gullwick, the moors of Saltreach, the isles of Shellstrand, the light on
// Stormhead, and Driftwood Bay, whose far road runs onto the sand.
import type { Giver, Quest } from '../quests.ts'

export let givers: Giver[] = [
  {
    id: 'kett',
    name: 'Harbourmaster Kett',
    level: 'gullwick',
    place: 'harbour',
    offset: [-1.5, -3],
    greets: 'Tide’s in, boats are tied. That’s a good day in Gullwick.',
    look: { tint: '#2a4a6a', hair: '#3a3a3a', skin: '#a87858' },
  },
  {
    id: 'marigold',
    name: 'Marigold Furrow',
    level: 'gullwick',
    place: 'harbour',
    offset: [6.5, -1],
    greets: 'Rows are straight, fence is up. A good day in the fields.',
    look: { tint: '#c9a23a', hair: '#b5562a', skin: '#e8b58f' },
  },
  {
    id: 'corrie',
    name: 'Corrie the shepherd',
    level: 'saltreach',
    place: 'moor',
    offset: [-15.5, 5.5],
    greets: 'Sheep, wind and salt. There’s worse lives.',
    look: { tint: '#8a7a5a', hair: '#e8e0d0', skin: '#e8c0a0' },
    staff: true,
  },
  {
    id: 'isla',
    name: 'Isla the pearl-diver',
    level: 'shellstrand',
    place: 'isles',
    offset: [-1.5, 10],
    greets:
      'The water’s cold and the pearls are few. I wouldn’t live anywhere else.',
    look: { tint: '#3a8a8a', hair: '#1a1a2a', skin: '#6a4a3a' },
  },
  {
    id: 'morrow',
    name: 'Keeper Morrow',
    level: 'stormhead',
    place: 'moor',
    offset: [2, -13.5],
    greets: 'The light is lit. Nothing else matters much.',
    look: { tint: '#6a4a2a', hair: '#a0a098', skin: '#b88868' },
  },
  {
    id: 'maddock',
    name: 'Maddock the wrecker',
    level: 'stormhead',
    place: 'coast',
    offset: [5.5, -9.5],
    greets: 'Every storm brings something ashore. Most of it is wet.',
    look: { tint: '#3a4a5a', hair: '#6a5a4a', skin: '#b08060' },
  },
  {
    id: 'anneke',
    name: 'Anneke the shipwright',
    level: 'driftwood',
    place: 'wharf',
    offset: [-1.5, -3],
    greets: 'A hull’s only as good as its worst plank.',
    look: { tint: '#7a5a3a', hair: '#e0c080', skin: '#f0c8a8' },
  },
  {
    id: 'dunn',
    name: 'Skipper Dunn',
    level: 'driftwood',
    place: 'wharf',
    offset: [6.5, -1],
    greets: 'Wind’s from the west. That’s a good wind, mostly.',
    look: { tint: '#2a3a5a', hair: '#8a6a4a', skin: '#c89878' },
  },
]

export let quests: Quest[] = [
  // Harbourmaster Kett, on the harbour at Gullwick.
  {
    id: 'kett-wolves',
    giver: 'kett',
    goal: 'slay',
    target: 'wolf',
    count: 5,
    xp: 320,
    title: 'Wolves on the quay',
    body:
      'Grey wolves come out of the woods south-west of the harbour at night and nose round the fish racks. Five of them, before they take somebody’s dog.',
  },
  {
    id: 'kett-fleece',
    giver: 'kett',
    after: 'kett-wolves',
    goal: 'gather',
    target: 'fleece',
    count: 4,
    xp: 600,
    title: 'Sailcloth',
    body:
      'We lost two sails in the storm off Stormhead. The wild rams on the meadow north-west of here grow good fleece for cloth. Four fleeces, and the boats go out again.',
  },
  {
    id: 'kett-warchief',
    giver: 'kett',
    after: 'kett-fleece',
    goal: 'slay',
    target: 'warchief',
    count: 1,
    xp: 340,
    title: 'Goblins on the harbour road',
    body:
      'A goblin warchief has taken to robbing the carts on the harbour road, briar in his helmet and a club in each hand. Put a stop to it.',
  },
  {
    id: 'kett-aurochs',
    giver: 'kett',
    after: 'kett-warchief',
    goal: 'slay',
    target: 'aurochs',
    count: 1,
    xp: 150,
    gift: 'tonic',
    title: 'Horns on the harbour road',
    body:
      'Now a longhorn aurochs has taken the road and won’t give it back. It has thorns in its hide, like the rest. Move it on for good. The light on Stormhead is out past Saltreach and the isles, if you’re looking for the east ward.',
  },
  // Marigold Furrow, who farms the meadow above Gullwick.
  {
    id: 'marigold-boars',
    giver: 'marigold',
    goal: 'slay',
    target: 'boar',
    count: 5,
    xp: 170,
    title: 'Tusks through the fence',
    body:
      'Bristleboars come down out of the woods and go through my fence like it’s straw. Drive off five before they find the turnips.',
  },
  {
    id: 'marigold-quillbacks',
    giver: 'marigold',
    after: 'marigold-boars',
    goal: 'slay',
    target: 'quillback',
    count: 4,
    xp: 250,
    title: 'Quills in the cabbages',
    body:
      'Quillbacks have moved into the cabbages, and they leave quills in everything, including me. Four of them, please.',
  },
  {
    id: 'marigold-bear',
    giver: 'marigold',
    after: 'marigold-quillbacks',
    goal: 'slay',
    target: 'bear',
    count: 1,
    xp: 180,
    gift: 'tonic',
    title: 'A bear in the barley',
    body:
      'A brown bear sleeps in my barley every afternoon, and flattens a new patch every day. Wake it, and send it off.',
  },
  // Corrie the shepherd, on the moor at Saltreach.
  {
    id: 'corrie-adders',
    giver: 'corrie',
    goal: 'slay',
    target: 'adder',
    count: 5,
    xp: 420,
    title: 'Adders in the heather',
    body:
      'Heath adders are thick in the heather this year, and the flock won’t graze. Five of them, and the sheep can eat.',
  },
  {
    id: 'corrie-bogles',
    giver: 'corrie',
    after: 'corrie-adders',
    goal: 'slay',
    target: 'bogle',
    count: 4,
    xp: 560,
    title: 'Bogles in the peat',
    body:
      'Bogles have come up out of the peat cuttings, and they steal the lambs for a joke. It is not a joke. Four of them.',
  },
  {
    id: 'corrie-golems',
    giver: 'corrie',
    after: 'corrie-bogles',
    goal: 'slay',
    target: 'golem',
    count: 2,
    xp: 720,
    gift: 'tonic',
    title: 'The standing stones',
    body:
      'The standing stones on the moor used to be where the sheep sheltered. Now two of them walk. Lay them down.',
  },
  {
    id: 'corrie-wyrms',
    giver: 'corrie',
    after: 'corrie-golems',
    goal: 'slay',
    target: 'stonewyrm',
    count: 3,
    xp: 620,
    gift: 'draught',
    title: 'The wyrms on the head',
    body:
      'Stonewyrms have come up out of the crags and sun themselves on the head where the sheep used to graze. They have briar in their scales. Three of them. The isles are down the road, if you’re going on to Stormhead.',
  },
  // Isla the pearl-diver, on the isles of Shellstrand.
  {
    id: 'isla-snapclaws',
    giver: 'isla',
    after: 'isla-pearl',
    goal: 'slay',
    target: 'snapclaw',
    count: 2,
    xp: 480,
    title: 'The big ones',
    body:
      'Snapclaws as big as barrows, with briar growing out of their shells, and they nip anyone wading out. Two of them, and I can dive again.',
  },
  {
    id: 'isla-seals',
    giver: 'isla',
    after: 'isla-snapclaws',
    goal: 'slay',
    target: 'seal',
    count: 3,
    xp: 370,
    title: 'Seals in the nets',
    body:
      'The seals were always friends of ours. Now they bite through the nets and snap at the divers. Three of them, and I’m sorry to ask.',
  },
  {
    id: 'isla-serpents',
    giver: 'isla',
    after: 'isla-seals',
    goal: 'slay',
    target: 'seaserpent',
    count: 3,
    xp: 790,
    gift: 'draught',
    title: 'Something in the channel',
    body:
      'Sea serpents have come into the channel between the isles. Nobody alive has seen one this close. Three of them. Then take the road on to Stormhead, and tell Keeper Morrow the pearl is from me.',
  },
  {
    id: 'isla-pearl',
    giver: 'isla',
    goal: 'gather',
    target: 'pearl',
    count: 1,
    xp: 1320,
    gift: 'tonic',
    title: 'One good pearl',
    body:
      'A pearl in the lamp throws its light twice as far, Keeper Morrow says. The serpents and the snapclaws carry one now and then, and the seals once in a blue moon. Bring me one, and I’ll send it up to the light on Stormhead.',
  },
  // Keeper Morrow, keeper of the light on Stormhead.
  {
    id: 'morrow-scorpions',
    giver: 'morrow',
    goal: 'slay',
    target: 'scorpion',
    count: 5,
    xp: 1030,
    title: 'Scorpions on the stair',
    body:
      'I keep the light on Stormhead, the east ward. The rocks round it are crawling with scorpions, and I climb up there every night. Five of them, and I can climb without a shield.',
  },
  {
    id: 'morrow-glow',
    giver: 'morrow',
    after: 'morrow-scorpions',
    goal: 'gather',
    target: 'glow',
    count: 4,
    xp: 1200,
    title: 'Wisplight for the lamp',
    body:
      'The Greenkeepers burned wisplight in the lamp, and the briar would not cross where it shone. The wisps on the moor carry it. Four lights.',
  },
  {
    id: 'morrow-wights',
    giver: 'morrow',
    after: 'morrow-glow',
    goal: 'slay',
    target: 'wight',
    count: 2,
    xp: 1420,
    title: 'The drowned sailors',
    body:
      'Sailors who drowned off the head have started walking up out of the sea, crowned in briar. Two of them. Let them rest.',
  },
  {
    id: 'morrow-basilisk',
    giver: 'morrow',
    after: 'morrow-wights',
    goal: 'slay',
    target: 'basilisk',
    count: 1,
    xp: 580,
    gift: 'elixir',
    title: 'The light is lit',
    body:
      'The light is lit, and I watched the briar pull back from the cliffs. But a basilisk has come up the crags to put it out. Kill it, and the east ward holds.',
  },
  // Maddock the wrecker, who picks the wrecks below Stormhead.
  {
    id: 'maddock-serpents',
    giver: 'maddock',
    goal: 'slay',
    target: 'seaserpent',
    count: 3,
    xp: 790,
    title: 'Serpents at the wrecks',
    body:
      'Sea serpents nest in the wrecks off the coast, and they don’t like sharing. Three of them, and the wrecks are mine to pick.',
  },
  {
    id: 'maddock-wyrms',
    giver: 'maddock',
    after: 'maddock-serpents',
    goal: 'slay',
    target: 'stonewyrm',
    count: 3,
    xp: 620,
    gift: 'draught',
    title: 'Wyrms on the cliff path',
    body:
      'The cliff path up from the coast is the only way to carry anything home, and stonewyrms sun themselves across it. Three of them.',
  },
  // Anneke the shipwright, on the wharf at Driftwood Bay.
  {
    id: 'anneke-bark',
    giver: 'anneke',
    goal: 'gather',
    target: 'bark',
    count: 5,
    xp: 700,
    title: 'A cart for the sands',
    body:
      'The far road out of the bay runs onto sand, and the last caravan down it came back begging for water. I’m building a water-cart for the next one. Five pieces of tough bark, from the barklings in the woods.',
  },
  {
    id: 'anneke-goblins',
    giver: 'anneke',
    after: 'anneke-bark',
    goal: 'slay',
    target: 'goblin',
    count: 4,
    xp: 330,
    title: 'Goblins in the timber yard',
    body:
      'Goblins come down out of the woods at night and carry off my timber, plank by plank, briar in their hair. Four of them, and the hull gets finished.',
  },
  {
    id: 'anneke-snapclaw',
    giver: 'anneke',
    after: 'anneke-goblins',
    goal: 'slay',
    target: 'snapclaw',
    count: 1,
    xp: 240,
    gift: 'tonic',
    title: 'Under the wharf',
    body:
      'A snapclaw has moved in under the wharf and cuts the mooring ropes for fun. Crack it, and the cart can take the road to Dustmere tomorrow. Go with it.',
  },
  // Skipper Dunn, mending nets on the Driftwood wharf.
  {
    id: 'dunn-gulls',
    giver: 'dunn',
    goal: 'slay',
    target: 'gull',
    count: 5,
    xp: 400,
    title: 'Gulls on the catch',
    body:
      'The harbour gulls have got bold, and bolder since the briar. They take the fish off the deck while I’m still pulling it in. Five of them.',
  },
  {
    id: 'dunn-bears',
    giver: 'dunn',
    after: 'dunn-gulls',
    goal: 'slay',
    target: 'bear',
    count: 2,
    xp: 360,
    title: 'Bears on the beach',
    body:
      'Brown bears come down to the beach for the fish heads, and now they come for the fishermen. Two of them.',
  },
  {
    id: 'dunn-brood',
    giver: 'dunn',
    after: 'dunn-bears',
    goal: 'slay',
    target: 'broodmother',
    count: 1,
    xp: 520,
    gift: 'draught',
    title: 'Webs in the rigging',
    body:
      'A broodmother nests in the woods up the bay, and her young come down and web up the rigging. Find her. Then I’ll row you anywhere you like.',
  },
]
