// The people of the vale: Mossvale, where every hero starts and Elder
// Wren teaches them before sending them down the west road; Birchmere and
// Clovermead, the green country round it; and the woods up the north road,
// from Fernwood to the Elder Heart and the pines of Wolfden.
import type { Giver, Quest } from '../quests.ts'

export let givers: Giver[] = [
  {
    id: 'wren',
    name: 'Elder Wren',
    level: 'mossvale',
    place: 'plaza',
    offset: [-1.5, -3],
    greets:
      'Four roads leave the vale, one to each edge of it: north to Fernwood, east to Reedmarsh, south to Stonestep and west to Birchmere. Every one of them has somebody on it who needs a hand.',
    look: { tint: '#4f7a4a', hair: '#e9e6df', skin: '#d9a98a' },
    staff: true,
  },
  {
    id: 'pip',
    name: 'Pip',
    level: 'mossvale',
    place: 'plaza',
    offset: [1, 5],
    greets: 'When I’m big I’m going to have a sword just like yours.',
    look: { tint: '#d9824a', hair: '#6b3f22', skin: '#f0c4a0' },
  },
  {
    id: 'alder',
    name: 'Reeve Alder',
    level: 'birchmere',
    place: 'green',
    offset: [-1.5, -3],
    greets:
      'Welcome to Birchmere. Any friend of Wren’s eats at my table, though she never writes.',
    look: { tint: '#6b5a8a', hair: '#cfcac0', skin: '#c9926e' },
    staff: true,
  },
  {
    id: 'sorrel',
    name: 'Sorrel the herbwife',
    level: 'birchmere',
    place: 'green',
    offset: [6.5, -1],
    greets: 'Mint for the head, moss for the heart, jelly for nearly anything.',
    look: { tint: '#7aa04a', hair: '#e0b05a', skin: '#f1c9a5' },
  },
  {
    id: 'mira',
    name: 'Mira of the mere',
    level: 'birchmere',
    place: 'mere',
    offset: [13, -8],
    greets: 'The mere is clear today. You can see all the way down.',
    look: { tint: '#4a8a9a', hair: '#1f1a18', skin: '#a86e4c' },
  },
  {
    id: 'fenn',
    name: 'Fenn the shepherd',
    level: 'birchmere',
    place: 'fields',
    offset: [11, 21.5],
    greets: 'The flock is grazing. That’s all a shepherd ever wants.',
    look: { tint: '#a07850', hair: '#e6e2da', skin: '#dca888' },
    staff: true,
  },
  {
    id: 'hazel',
    name: 'Hazel the woodcutter',
    level: 'birchmere',
    place: 'woods',
    offset: [-5, 19.5],
    greets: 'Mind the chips. They fly further than you think.',
    look: { tint: '#8a4a3a', hair: '#4a2e1c', skin: '#e2b08a' },
  },
  {
    id: 'mab',
    name: 'Mab the beekeeper',
    level: 'clovermead',
    place: 'meadow',
    offset: [-2, -4],
    greets: 'Hear that hum? That’s a happy hive. Mind where you step.',
    look: { tint: '#e0b33a', hair: '#8a8a82', skin: '#c98f6a' },
    staff: true,
  },
  {
    id: 'oriel',
    name: 'Warden Oriel',
    level: 'fernwood',
    place: 'glade',
    offset: [-1.5, -3],
    greets: 'The glade is quiet. I don’t trust it when it’s quiet.',
    look: { tint: '#2f5a3a', hair: '#c46a2a', skin: '#e8b48c' },
  },
  {
    id: 'bryony',
    name: 'Bryony the forager',
    level: 'fernwood',
    place: 'glade',
    offset: [6.5, -1],
    greets:
      'Mushrooms, nuts, silk, honey. The wood gives, if you ask it nicely.',
    look: { tint: '#9a6a3a', hair: '#3a2418', skin: '#7a4a30' },
  },
  {
    id: 'hollis',
    name: 'Hollis the woodward',
    level: 'fernwood',
    place: 'glade',
    offset: [1, 5],
    greets: 'Listen to the trees a while. They say more than folk think.',
    look: { tint: '#3f6b3a', hair: '#7a5a3a', skin: '#c68c64' },
  },
  {
    id: 'ysolde',
    name: 'Ysolde the Greenwarden',
    level: 'elderglade',
    place: 'heart',
    offset: [-5.5, 24],
    greets: 'The Elder Heart still beats. Slowly, but it beats.',
    look: { tint: '#3a6b4a', hair: '#f0ead8', skin: '#b98260' },
    staff: true,
  },
  {
    id: 'hake',
    name: 'Hake the trapper',
    level: 'greypine',
    place: 'pines',
    offset: [-3, 14],
    greets: 'Set a snare, wait. Set another. That’s the whole trade.',
    look: { tint: '#6a5a3a', hair: '#5a4a3a', skin: '#d0a080' },
  },
  {
    id: 'brenna',
    name: 'Brenna of the Den',
    level: 'wolfden',
    place: 'pines',
    offset: [14.5, 20],
    greets: 'The den keeps its own. You’re welcome at the fire.',
    look: { tint: '#5a3a3a', hair: '#b0b0a8', skin: '#8a5a40' },
  },
]

export let quests: Quest[] = [
  // Elder Wren, the spine of the story, by the Mossvale fire.
  {
    id: 'wren-jelly',
    giver: 'wren',
    goal: 'gather',
    target: 'jelly',
    count: 4,
    xp: 70,
    gift: 'tonic',
    title: 'Jelly for the kettle',
    body:
      'The moss slimes out in the meadow are fat with jelly this season. Bring me four and I will brew you a tonic that mends a bruise or two.',
  },
  {
    id: 'wren-boars',
    giver: 'wren',
    after: 'wren-jelly',
    goal: 'slay',
    target: 'boar',
    count: 4,
    xp: 140,
    gift: 'blade2',
    title: 'Bristles in the turnips',
    body:
      'Bristleboars are rooting up the edge of Whisperwood, north of here, and my turnips with it. Drive off four of them, and take my old blade, Boarsbane, for your trouble.',
  },
  {
    id: 'wren-crags',
    giver: 'wren',
    after: 'wren-boars',
    goal: 'slay',
    target: 'crag',
    count: 3,
    xp: 240,
    gift: 'blade3',
    title: 'The stones that walk',
    body:
      'Up in Craghollow, to the south-west, the rocks have started walking. Cragbacks, the old folk called them. Topple three, and this cleaver is yours. Then take the west road to Birchmere: Reeve Alder keeps an old book, and I want to know what it says about thorns.',
  },
  {
    id: 'wren-thornback',
    giver: 'wren',
    after: 'wren-crags',
    goal: 'slay',
    target: 'thornback',
    count: 1,
    xp: 600,
    gift: 'draught',
    title: 'Old Thornback',
    body:
      'Something old nests on Thornback Ridge, south-east of the village, and every beast in the vale is restless because of it. It is too much for you yet. Walk the roads, come back stronger, and bring friends.',
  },
  {
    id: 'wren-crown',
    giver: 'wren',
    after: 'wren-thornback',
    goal: 'gather',
    target: 'crown',
    count: 1,
    xp: 300,
    gift: 'draught',
    title: 'A crown of briar',
    body:
      'Old Thornback did not grow that crown. Somebody set it on him, and the Reeve’s book says who: the briar itself, crowning what it wakes. Give it here, and I will keep it where I can watch it.',
  },
  {
    id: 'wren-home',
    giver: 'wren',
    after: 'garrow-wyrm',
    level: 'maw',
    goal: 'gather',
    target: 'ember',
    count: 1,
    xp: 2000,
    gift: 'elixir',
    title: 'Fire for the hearth',
    body:
      'You went all the way to the Maw and came back. Every hearth in the vale was lit from the deep fire once, before the briar. Give me an ember from down there, and the plaza fire will burn clean again.',
  },
  // Pip, who wants to be you.
  {
    id: 'pip-slimes',
    giver: 'pip',
    goal: 'slay',
    target: 'slime',
    count: 5,
    xp: 70,
    title: 'The ball that got away',
    body:
      'A slime swallowed my ball, down past the last lamp. I don’t know which one. If you pop five, it has to be in one of them, right?',
  },
  {
    id: 'pip-feathers',
    giver: 'pip',
    after: 'pip-slimes',
    goal: 'gather',
    target: 'feather',
    count: 3,
    xp: 45,
    title: 'A hat for a hero',
    body:
      'No ball. Never mind. I’m making a hat now, a hero hat, with feathers in. The hens and ducks round the village drop the best ones. Three, please.',
  },
  // Reeve Alder, who keeps the old book in Birchmere.
  {
    id: 'alder-thorns',
    giver: 'alder',
    after: 'wren-crags',
    goal: 'slay',
    target: 'boar',
    count: 6,
    xp: 200,
    gift: 'tonic',
    title: 'The Reeve of Birchmere',
    body:
      'So Wren sent you. She writes that Mossvale’s beasts have thorns in them now, and so do ours: the boars in Emberwood, south-east of the green, have briar in their hides. Drive off six, and I’ll open the old book.',
  },
  {
    id: 'alder-tusks',
    giver: 'alder',
    after: 'alder-thorns',
    goal: 'gather',
    target: 'tusk',
    count: 5,
    xp: 260,
    title: 'Proof for the council',
    body:
      'The council laughs at thorns in a boar. It won’t laugh at five tusks on the table, thorns and all. Bring them, and we’ll see who laughs.',
  },
  {
    id: 'alder-ring',
    giver: 'alder',
    after: 'alder-tusks',
    level: 'mossvale',
    goal: 'gather',
    target: 'shard',
    count: 3,
    xp: 400,
    gift: 'tonic',
    title: 'The Greenkeepers’ ring',
    body:
      'The book says the Greenkeepers held the briar back with a ring of crag shards. There are no crags in Birchmere. Take the road back to Mossvale, climb into Craghollow, and bring me three.',
  },
  {
    id: 'alder-gates',
    giver: 'alder',
    after: 'alder-ring',
    goal: 'slay',
    target: 'goblin',
    count: 5,
    xp: 420,
    gift: 'draught',
    title: 'Four roads',
    body:
      'Bramble goblins came up the road last night with briar in their hair. The book says the Greenkeepers set a ward at the end of each road out of Mossvale: the Elder Heart up the north road, the bell of the Sunken Kirk down the east road, the old king’s barrow down the south road, and the light on Stormhead, out past Gullwick on our own west road. Drive off five goblins, then go and see if the wards still hold.',
  },
  // Sorrel the herbwife, by the well in Birchmere.
  {
    id: 'sorrel-jelly',
    giver: 'sorrel',
    goal: 'gather',
    target: 'jelly',
    count: 6,
    xp: 100,
    gift: 'tonic',
    title: 'Jelly and patience',
    body:
      'A tonic is mostly slime jelly and patience. I have the patience. Six jellies, and one of the tonics is yours.',
  },
  {
    id: 'sorrel-slimes',
    giver: 'sorrel',
    after: 'sorrel-jelly',
    goal: 'slay',
    target: 'slime',
    count: 10,
    xp: 140,
    title: 'In the herb beds',
    body:
      'The slimes have found my herb beds, and they don’t leave much. Ten of them, please, and step softly round the mint.',
  },
  {
    id: 'sorrel-tusks',
    giver: 'sorrel',
    after: 'sorrel-slimes',
    goal: 'gather',
    target: 'tusk',
    count: 2,
    xp: 100,
    gift: 'tonic',
    title: 'A poultice for the flock',
    body:
      'Fenn’s sheep keep getting gored. Boar tusk, ground fine, draws the swelling out. Two tusks, and take a tonic for the road.',
  },
  // Mira of the mere, on the shore of the Birchmere mere.
  {
    id: 'mira-slimes',
    giver: 'mira',
    after: 'mira-jelly',
    goal: 'slay',
    target: 'slime',
    count: 8,
    xp: 110,
    title: 'Clouded water',
    body:
      'Slimes slide into the mere to cool off and cloud it green for days. Clear eight of them off the shore, and the water will settle.',
  },
  {
    id: 'mira-jelly',
    giver: 'mira',
    goal: 'gather',
    target: 'jelly',
    count: 4,
    xp: 70,
    title: 'Lamps for the jetty',
    body:
      'Slime jelly glows a little in a jar after dark. Four jars along the jetty, and the boats find their way home.',
  },
  {
    id: 'mira-snakes',
    giver: 'mira',
    after: 'mira-slimes',
    goal: 'slay',
    target: 'watersnake',
    count: 2,
    xp: 210,
    gift: 'tonic',
    title: 'Something in the reeds',
    body:
      'A water snake has moved into the reeds by the jetty, then another. Two of them, and the children can paddle again.',
  },
  // Fenn the shepherd, in the north-west fields of Birchmere.
  {
    id: 'fenn-boars',
    giver: 'fenn',
    after: 'fenn-tusks',
    goal: 'slay',
    target: 'boar',
    count: 6,
    xp: 200,
    title: 'Sheep in a panic',
    body:
      'The boars come out of the Whitebirches, off to the east, and run my sheep ragged. They never used to. Six of them, and my flock might eat again.',
  },
  {
    id: 'fenn-tusks',
    giver: 'fenn',
    goal: 'gather',
    target: 'tusk',
    count: 3,
    xp: 160,
    gift: 'tonic',
    title: 'A fence of tusks',
    body:
      'An old trick: tusks set in the gatepost, points out. A boar smells its own kind and turns away. Three should do the gate.',
  },
  {
    id: 'fenn-adders',
    giver: 'fenn',
    after: 'fenn-boars',
    goal: 'slay',
    target: 'adder',
    count: 3,
    xp: 250,
    title: 'Adders in the grass',
    body:
      'Heath adders in the long grass now, and a bitten ewe is a lost ewe. Three of them, and I’ll sleep tonight.',
  },
  // Hazel the woodcutter, below the Whitebirches.
  {
    id: 'hazel-boars',
    giver: 'hazel',
    goal: 'slay',
    target: 'boar',
    count: 8,
    xp: 270,
    title: 'Axes down',
    body:
      'We can’t fell a birch without a Bristleboar coming at us out of the bracken. Eight of them, and we’ll get back to work.',
  },
  {
    id: 'hazel-hornets',
    giver: 'hazel',
    after: 'hazel-boars',
    goal: 'slay',
    target: 'hornet',
    count: 4,
    xp: 240,
    gift: 'tonic',
    title: 'A nest in the birches',
    body:
      'Now the hornets. They’ve built a nest the size of a barrel in the Whitebirches, and they don’t like axes. Four of them, and I’ll smoke out the rest.',
  },
  // Mab the beekeeper, in the middle of Clovermead.
  {
    id: 'mab-glimmers',
    giver: 'mab',
    goal: 'slay',
    target: 'glimmer',
    count: 4,
    xp: 420,
    title: 'Lights in the clover',
    body:
      'Glimmer wisps drift over the meadow at dusk, and the bees follow them away and never come home. Four of them, and my hives stay full.',
  },
  {
    id: 'mab-spiders',
    giver: 'mab',
    after: 'mab-glimmers',
    goal: 'slay',
    target: 'spider',
    count: 6,
    xp: 270,
    title: 'Webs on the hives',
    body:
      'Wood spiders are coming out of the trees north-west of here and webbing up my hives. Six of them, and the bees can fly again.',
  },
  {
    id: 'mab-bear',
    giver: 'mab',
    after: 'mab-spiders',
    goal: 'slay',
    target: 'bear',
    count: 1,
    xp: 180,
    gift: 'tonic',
    title: 'A bear with a sweet tooth',
    body:
      'A brown bear has found the hives, and a bear that has found honey never forgets the way. Send it back to the woods for good.',
  },
  {
    id: 'mab-warchief',
    giver: 'mab',
    after: 'mab-bear',
    goal: 'slay',
    target: 'warchief',
    count: 1,
    xp: 340,
    gift: 'draught',
    title: 'The goblin who wants my honey',
    body:
      'A goblin warchief has been through the meadow twice, sizing up my hives, with briar in his helmet. He’ll be back with his friends. Get to him first.',
  },
  // Warden Oriel, warden of the glade in Fernwood.
  {
    id: 'oriel-goblins',
    giver: 'oriel',
    goal: 'slay',
    target: 'goblin',
    count: 6,
    xp: 500,
    title: 'Briar in the glade',
    body:
      'Bramble goblins come into the glade at night now, wearing briar like crowns, the same as the beasts. Drive off six, and I’ll tell you what I know about the Elder Heart.',
  },
  {
    id: 'oriel-stag',
    giver: 'oriel',
    after: 'oriel-goblins',
    goal: 'slay',
    target: 'stag',
    count: 1,
    xp: 110,
    gift: 'tonic',
    title: 'The stag in the thorns',
    body:
      'The goblins follow a great stag with briar grown through its antlers, as if it were their king. Bring it down, and they scatter. Then take the road north to Elderglade: the Greenwarden there tends the Elder Heart, the north ward.',
  },
  // Bryony the forager, by the well in the Fernwood glade.
  {
    id: 'bryony-caps',
    giver: 'bryony',
    goal: 'gather',
    target: 'cap',
    count: 4,
    xp: 410,
    title: 'Caps for the pot',
    body:
      'The caplings grow the best mushroom caps in Fernwood, and they don’t give them up without a fuss. Four caps for the pot, please.',
  },
  {
    id: 'bryony-silk',
    giver: 'bryony',
    after: 'bryony-caps',
    goal: 'gather',
    target: 'silk',
    count: 4,
    xp: 300,
    gift: 'tonic',
    title: 'Thread for the winter',
    body:
      'Spider silk makes the warmest thread there is, if you can get it off the spider. Four skeins, and I’ll knit you something. Well. I’ll give you a tonic.',
  },
  // Hollis the woodward, by the Fernwood fire.
  {
    id: 'hollis-boars',
    giver: 'hollis',
    goal: 'slay',
    target: 'boar',
    count: 5,
    xp: 170,
    title: 'A restless herd',
    body:
      'The boars in these woods used to shy at a snapped twig. Now they charge a woodward with his axe up. Five of them, before somebody’s hurt.',
  },
  {
    id: 'hollis-barklings',
    giver: 'hollis',
    after: 'hollis-boars',
    goal: 'slay',
    target: 'barkling',
    count: 4,
    xp: 340,
    gift: 'tonic',
    title: 'Twigs that walk',
    body:
      'The barklings were always here, little walking twigs, harmless. Now they have thorns, and they go for the saplings. Four of them, and the young wood has a chance.',
  },
  // Ysolde the Greenwarden, the last Greenwarden, under the Elder Heart.
  {
    id: 'ysolde-barklings',
    giver: 'ysolde',
    goal: 'slay',
    target: 'barkling',
    count: 8,
    xp: 670,
    title: 'Twigs of the Elder',
    body:
      'This is the Elder Heart, the oldest tree there is, and I am its last Greenwarden. Its fallen twigs grow up into barklings, and the briar has got into them. Put eight to rest.',
  },
  {
    id: 'ysolde-direwolves',
    giver: 'ysolde',
    after: 'ysolde-barklings',
    goal: 'slay',
    target: 'direwolf',
    count: 2,
    xp: 800,
    gift: 'draught',
    title: 'Wolves at the roots',
    body:
      'Dire wolves have made their dens among the Elder’s roots, and they gnaw at them. Two of them. The roots run west of the Heart, down under the wood to Glowcap Hollow, if you ever want to follow them.',
  },
  {
    id: 'ysolde-heartwood',
    giver: 'ysolde',
    after: 'ysolde-direwolves',
    level: 'mirewood',
    goal: 'gather',
    target: 'heartwood',
    count: 1,
    xp: 1050,
    gift: 'blade4',
    title: 'A graft of heartwood',
    body:
      'To mend the gnawed roots I need living heartwood, and only a Grimbark still carries any. They walk in Mirewood now, out along the east road from Mossvale, past Reedmarsh. Bring me heartwood, and I will make you a blade from what the graft does not need.',
  },
  // Hake the trapper, in the pines of Greypine.
  {
    id: 'hake-wolves',
    giver: 'hake',
    after: 'hake-pelts',
    goal: 'slay',
    target: 'wolf',
    count: 6,
    xp: 380,
    title: 'Too many wolves',
    body:
      'Grey wolves by the dozen in these pines, and they’ve stopped running from a man with a torch. Six of them, and my lines might see morning.',
  },
  {
    id: 'hake-pelts',
    giver: 'hake',
    goal: 'gather',
    target: 'pelt',
    count: 4,
    xp: 340,
    title: 'Furs for the winter',
    body:
      'The winter up here takes the ears off a man. Four good pelts, and I’ll line a coat for whoever needs it most.',
  },
  {
    id: 'hake-lynx',
    giver: 'hake',
    after: 'hake-wolves',
    goal: 'slay',
    target: 'lynx',
    count: 1,
    xp: 130,
    gift: 'tonic',
    title: 'Followed home',
    body:
      'A ridge lynx has taken to following me home, rock to rock, never closer than a stone’s throw. I’d like to walk home alone again.',
  },
  {
    id: 'hake-direwolf',
    giver: 'hake',
    after: 'hake-lynx',
    goal: 'slay',
    target: 'direwolf',
    count: 1,
    xp: 400,
    gift: 'draught',
    title: 'The one that leads them',
    body:
      'The wolves follow a dire wolf, big as a pony, with briar round its neck like a collar. Kill it, and the rest lose their nerve. Then go on east to Wolfden, if you’re going: that’s where they all come from.',
  },
  // Brenna of the Den, in the pines of Wolfden.
  {
    id: 'brenna-kobolds',
    giver: 'brenna',
    goal: 'slay',
    target: 'kobold',
    count: 6,
    xp: 500,
    title: 'Kobolds in the crags',
    body:
      'Crag kobolds have dug into the rocks east of here, and they steal anything with an edge. Six of them, and we get our knives back.',
  },
  {
    id: 'brenna-scorpions',
    giver: 'brenna',
    after: 'brenna-kobolds',
    goal: 'slay',
    target: 'scorpion',
    count: 4,
    xp: 820,
    title: 'Stings in the scree',
    body:
      'Rock scorpions have crawled up out of the scree, and they don’t belong this far north. Something is driving everything up the mountain. Four of them.',
  },
  {
    id: 'brenna-golems',
    giver: 'brenna',
    after: 'brenna-scorpions',
    goal: 'slay',
    target: 'golem',
    count: 2,
    xp: 720,
    gift: 'tonic',
    title: 'Stones that wake',
    body:
      'The old stone keepers in the crags have woken with briar in their seams. Two of them, before they come down to the den.',
  },
  {
    id: 'brenna-wyrms',
    giver: 'brenna',
    after: 'brenna-golems',
    goal: 'slay',
    target: 'stonewyrm',
    count: 3,
    xp: 620,
    gift: 'draught',
    title: 'Wyrms in the rock',
    body:
      'It was stonewyrms that drove the kobolds out of the high rocks, briar-crowned like everything else now. Three of them. Then take the road east into the snow: the wolves have been coming down from Frostmoor.',
  },
]
