// The people of the west road out of Mossvale: the stilt-town of
// Reedmarsh, Mirewood and Fenhollow, the Sunken Kirk whose bell kept the
// bog asleep, and Bogheart, where the briar has a root.
import type { Giver, Quest } from '../quests.ts'

export let givers: Giver[] = [
  {
    id: 'nell',
    name: 'Nell of the Stilts',
    level: 'reedmarsh',
    place: 'stilts',
    offset: [-1.5, -3],
    greets: 'Walk the boards, not the bog, and you’ll keep your boots.',
    look: { tint: '#4a6a6a', hair: '#7a3a2a', skin: '#c08a6a' },
  },
  {
    id: 'wade',
    name: 'Wade the reed-cutter',
    level: 'reedmarsh',
    place: 'stilts',
    offset: [6.5, -1],
    greets: 'Reeds for thatch, reeds for baskets, reeds for everything.',
    look: { tint: '#7a8a4a', hair: '#c0a060', skin: '#e0b890' },
  },
  {
    id: 'tamsin',
    name: 'Old Tamsin',
    level: 'reedmarsh',
    place: 'stilts',
    offset: [1, 5],
    greets: 'Sit. The fish don’t mind company, so long as it’s quiet.',
    look: { tint: '#3f6f8f', hair: '#d8d4cc', skin: '#b77b55' },
    staff: true,
  },
  {
    id: 'sedge',
    name: 'Old Sedge',
    level: 'mirewood',
    place: 'marsh',
    offset: [-3.5, 5.5],
    greets: 'The mire keeps what it takes. Mostly.',
    look: { tint: '#4a5a3a', hair: '#d8d0c0', skin: '#9a6a4a' },
    staff: true,
  },
  {
    id: 'maud',
    name: 'Digger Maud',
    level: 'fenhollow',
    place: 'ruins',
    offset: [5.5, 12.5],
    greets: 'Every stone here has a story. Most of them are about drains.',
    look: { tint: '#8a6a4a', hair: '#4a3a2a', skin: '#e0a888' },
  },
  {
    id: 'tobin',
    name: 'Brother Tobin',
    level: 'sunkenkirk',
    place: 'kirk',
    offset: [10, 7],
    greets: 'The bell rings at dusk. Stay and hear it.',
    look: { tint: '#5a4a6a', hair: '#d0c8b8', skin: '#d8a888' },
  },
  {
    id: 'rush',
    name: 'Granny Rush',
    level: 'bogheart',
    place: 'marsh',
    offset: [8.5, -1.5],
    greets: 'Sit, sit. The kettle’s on. It’s always on.',
    look: { tint: '#3a4a3a', hair: '#9aa090', skin: '#8a6a50' },
    staff: true,
  },
]

export let quests: Quest[] = [
  // Nell of the Stilts, who runs the stilt-town of Reedmarsh.
  {
    id: 'nell-bogslimes',
    giver: 'nell',
    goal: 'slay',
    target: 'bogslime',
    count: 5,
    xp: 420,
    title: 'Slime on the boards',
    body:
      'Bog slimes crawl up onto the boardwalks and ooze across the planks, and the planks rot under them. Five of them, please, before we’re all in the water.',
  },
  {
    id: 'nell-snakes',
    giver: 'nell',
    after: 'nell-bogslimes',
    goal: 'slay',
    target: 'watersnake',
    count: 3,
    xp: 320,
    title: 'Snakes under the stilts',
    body:
      'Water snakes coil round the stilts under the houses and drop onto the boards at night. Three of them, and I’ll stop checking my boots.',
  },
  {
    id: 'nell-aurochs',
    giver: 'nell',
    after: 'nell-snakes',
    goal: 'slay',
    target: 'aurochs',
    count: 1,
    xp: 150,
    gift: 'draught',
    title: 'The ferry-pool',
    body:
      'A longhorn aurochs wallows in the ferry-pool with briar in its hide, and nobody will take the ferry. Move it on. Then take the road on to Mirewood, and past it the Sunken Kirk: its bell used to keep the bog asleep.',
  },
  // Wade the reed-cutter, by the well in Reedmarsh.
  {
    id: 'wade-dust',
    giver: 'wade',
    goal: 'gather',
    target: 'dust',
    count: 4,
    xp: 55,
    title: 'Dust for the dye',
    body:
      'The moths and blue darters over the reeds shed a wing dust that makes the finest dye. Four pinches, and my baskets fetch twice the price.',
  },
  {
    id: 'wade-herons',
    giver: 'wade',
    after: 'wade-dust',
    goal: 'slay',
    target: 'heron',
    count: 3,
    xp: 130,
    title: 'Herons at the eel traps',
    body:
      'The herons have learned to open my eel traps. Clever birds. Too clever. Three of them, and the eels are mine again.',
  },
  {
    id: 'wade-beaver',
    giver: 'wade',
    after: 'wade-herons',
    goal: 'slay',
    target: 'beaver',
    count: 1,
    xp: 40,
    gift: 'tonic',
    title: 'The dam',
    body:
      'A beaver has dammed my best channel, and the reeds behind it are drowning. It has thorns in its tail, of all things. See it off.',
  },
  // Old Tamsin, who fishes off the Reedmarsh boards.
  {
    id: 'tamsin-bait',
    giver: 'tamsin',
    goal: 'gather',
    target: 'jelly',
    count: 3,
    xp: 50,
    title: 'The best bait',
    body:
      'Slime jelly is the best bait there ever was, and bog slime jelly better still. Bring me three, and I’ll tell you a story while the float bobs.',
  },
  {
    id: 'tamsin-stones',
    giver: 'tamsin',
    after: 'tamsin-bait',
    level: 'mossvale',
    goal: 'gather',
    target: 'shard',
    count: 2,
    xp: 270,
    gift: 'tonic',
    title: 'The Greenkeepers',
    body:
      'Long ago the Greenkeepers planted the moss, and the beasts grew gentle in it. They set crag shards round every water to keep the briar out, and ours are long gone. The crags back in Mossvale still have shards. Bring me two, and I’ll set them round this one.',
  },
  // Old Sedge, in the middle of Mirewood.
  {
    id: 'sedge-goblins',
    giver: 'sedge',
    goal: 'slay',
    target: 'goblin',
    count: 6,
    xp: 500,
    title: 'Goblin fires',
    body:
      'Goblins have lit fires all through Mirewood, and the smoke smells of briar. Scatter six of them, and put their fires out while you’re at it.',
  },
  {
    id: 'sedge-lanterns',
    giver: 'sedge',
    after: 'sedge-goblins',
    goal: 'slay',
    target: 'lantern',
    count: 3,
    xp: 460,
    title: 'Lights over the mire',
    body:
      'The mire lanterns lead folk off the paths and into the deep bog, and they’ve been busy since the briar came. Snuff three of them.',
  },
  {
    id: 'sedge-bears',
    giver: 'sedge',
    after: 'sedge-lanterns',
    goal: 'slay',
    target: 'bear',
    count: 2,
    xp: 360,
    gift: 'tonic',
    title: 'Bears in the berries',
    body:
      'Two brown bears have taken the berry thickets, and they’ve got briar in their coats. The mire folk need those berries for the winter. See the bears off.',
  },
  {
    id: 'sedge-grimbark',
    giver: 'sedge',
    after: 'sedge-bears',
    goal: 'slay',
    target: 'grimbark',
    count: 1,
    xp: 1050,
    gift: 'draught',
    title: 'The bog spreads',
    body:
      'A Grimbark walks these woods with the briar in its heart, and everywhere it steps, the bog spreads. Fell it. If the Greenwarden in Elderglade asks after its heartwood, she’s welcome to it. The road on runs to Fenhollow.',
  },
  // Digger Maud, at her dig in the Fenhollow ruins.
  {
    id: 'maud-kobolds',
    giver: 'maud',
    goal: 'slay',
    target: 'kobold',
    count: 6,
    xp: 500,
    title: 'Diggers in my dig',
    body:
      'Crag kobolds have moved into my ruins, and they dig faster than I do. Six of them, and I get my trench back.',
  },
  {
    id: 'maud-wisps',
    giver: 'maud',
    after: 'maud-kobolds',
    goal: 'slay',
    target: 'wisp',
    count: 4,
    xp: 720,
    title: 'Lights in the ruins',
    body:
      'Wisps drift over the ruins at night and lead my diggers into the pools. I’ve lost two shovels and nearly a nephew. Four of them.',
  },
  {
    id: 'maud-troll',
    giver: 'maud',
    after: 'maud-wisps',
    goal: 'slay',
    target: 'troll',
    count: 1,
    xp: 520,
    gift: 'tonic',
    title: 'A troll in the trench',
    body:
      'A mire troll has fallen asleep in my best trench, and I am not asking it to move. You ask it.',
  },
  {
    id: 'maud-golems',
    giver: 'maud',
    after: 'maud-troll',
    goal: 'slay',
    target: 'golem',
    count: 2,
    xp: 720,
    gift: 'draught',
    title: 'The keepers of the waystation',
    body:
      'These ruins were a Greenkeeper waystation, and its stone keepers never stirred in forty years of my digging. Now they walk, with briar in their seams. Lay two of them down. The road on from here runs to the Sunken Kirk.',
  },
  // Brother Tobin, the last bellringer of the Sunken Kirk.
  {
    id: 'tobin-ore',
    giver: 'tobin',
    goal: 'gather',
    target: 'ore',
    count: 3,
    xp: 1350,
    title: 'A cracked bell',
    body:
      'The bell of the Sunken Kirk is the west ward, and it has cracked. Without the bell, the bog wakes. The stone keepers out on the marsh carry iron in them. Three lumps, and I can mend it.',
  },
  {
    id: 'tobin-trolls',
    giver: 'tobin',
    after: 'tobin-ore',
    goal: 'slay',
    target: 'troll',
    count: 2,
    xp: 1030,
    title: 'Trolls in the nave',
    body:
      'Two mire trolls have made their beds in the flooded nave, and they don’t care for bells. Clear them out, so I can climb the tower.',
  },
  {
    id: 'tobin-scarabs',
    giver: 'tobin',
    after: 'tobin-trolls',
    goal: 'slay',
    target: 'scarab',
    count: 4,
    xp: 1050,
    title: 'Beetles in the crypt',
    body:
      'Tomb scarabs have got into the crypt under the chapel. They eat the dead, and they don’t much mind the living. Four of them.',
  },
  {
    id: 'tobin-lanterns',
    giver: 'tobin',
    after: 'tobin-scarabs',
    goal: 'slay',
    target: 'lantern',
    count: 4,
    xp: 620,
    gift: 'draught',
    title: 'The bell rings',
    body:
      'The bell rang, and the briar in the reeds drew back. But the mire lanterns gather to it like moths. Snuff four. Then take the road on to Bogheart: Granny Rush says the briar has a root there.',
  },
  // Granny Rush, at the heart of the bog.
  {
    id: 'rush-sporelings',
    giver: 'rush',
    goal: 'slay',
    target: 'sporeling',
    count: 4,
    xp: 820,
    title: 'Spores on the wind',
    body:
      'Sporelings drift over from the toadstools, and everything they touch grows briar. Burst four of them, dear.',
  },
  {
    id: 'rush-trolls',
    giver: 'rush',
    after: 'rush-sporelings',
    goal: 'slay',
    target: 'troll',
    count: 2,
    xp: 1030,
    title: 'Trolls at the kettle',
    body:
      'Two trolls come round every evening for my kettle, and they don’t bring cups. See them off.',
  },
  {
    id: 'rush-wights',
    giver: 'rush',
    after: 'rush-trolls',
    goal: 'slay',
    target: 'wight',
    count: 2,
    xp: 1420,
    gift: 'draught',
    title: 'The drowned',
    body:
      'The bog keeps what it takes, and now the briar is waking it. The drowned walk at night, crowned in thorns. Put two of them back to rest.',
  },
  {
    id: 'rush-mudjaw',
    giver: 'rush',
    after: 'rush-wights',
    goal: 'slay',
    target: 'mudjaw',
    count: 2,
    xp: 2320,
    gift: 'elixir',
    title: 'The old toad',
    body:
      'The briar has a root in Bogheart, and Old Mudjaw sits on it like an egg, a toad as big as a cart. Put him down, and when he comes back, put him down again. Then the root will wither, and that’s the west road done.',
  },
]
