// The creatures under the old woods: the capling folk of the giant
// toadstools and what drifts among them, and deeper down, in the crystal,
// the shardlings, the glimmerbacks and the Hollow King.
import type { Beast } from '../beasts.ts'

export let DEEP: Record<string, Beast> = {
  capling: {
    name: 'Capling',
    lvl: 2,
    hp: 48,
    dmg: 5,
    speed: 2.2,
    xp: 24,
    reach: 1.2,
    aggro: 0,
    respawn: 20,
    loot: [['cap', 0.7], ['spore', 0.3]],
    size: 0.8,
    dust: 0xd84a3a,
    haunts: [
      { near: 'woods', count: 2, within: 22, apart: 6, roam: 4, odds: 0.4 },
      {
        near: 'shroomwood',
        count: 3,
        within: 26,
        apart: 6,
        roam: 4,
        odds: 0.7,
      },
    ],
    look: {
      plan: 'biped',
      skin: 0xefe4cc,
      garb: 0xe8dcc0,
      eye: 0x2a1a10,
      head: 'cap',
      top: 0xd8483a,
      build: [0.9, 0.55],
      scale: 0.9,
    },
  },
  stoolbrute: {
    name: 'Toadstool brute',
    lvl: 6,
    hp: 280,
    dmg: 17,
    speed: 2.4,
    xp: 110,
    reach: 2,
    aggro: 5,
    respawn: 40,
    loot: [['cap', 0.8], ['spore', 0.6], ['coin', 0.4]],
    size: 1.5,
    dust: 0x8a5aa8,
    haunts: [
      {
        near: 'shroomwood',
        count: 1,
        within: 20,
        apart: 10,
        roam: 4,
        odds: 0.6,
      },
    ],
    look: {
      plan: 'biped',
      skin: 0xe8dcc0,
      garb: 0xd8ccb0,
      eye: 0x2a1a10,
      head: 'cap',
      top: 0x7a4aa8,
      build: [1.4, 0.9],
      long: true,
      scale: 1.5,
    },
  },
  sporeling: {
    name: 'Sporeling',
    lvl: 8,
    hp: 320,
    dmg: 20,
    speed: 2.8,
    xp: 154,
    reach: 1.5,
    aggro: 7,
    respawn: 40,
    loot: [['spore', 0.8], ['glow', 0.3], ['coin', 0.4]],
    size: 0.8,
    dust: 0xc8a0f0,
    haunts: [
      {
        near: 'shroomwood',
        count: 2,
        within: 26,
        apart: 8,
        roam: 6,
        odds: 0.6,
      },
    ],
    look: {
      plan: 'wisp',
      core: 0xf0e0ff,
      glow: 0xb07ae0,
      mote: 0xe0c0ff,
      fly: 0.6,
      scale: 0.9,
    },
  },
  glimmer: {
    name: 'Glimmer wisp',
    lvl: 4,
    hp: 120,
    dmg: 12,
    speed: 3,
    xp: 63,
    reach: 1.4,
    aggro: 6,
    respawn: 30,
    loot: [['glow', 0.5], ['coin', 0.3]],
    size: 0.7,
    dust: 0xd8f070,
    haunts: [
      { near: 'woods', count: 2, within: 20, apart: 10, roam: 7, odds: 0.4 },
      {
        near: 'shroomwood',
        count: 2,
        within: 24,
        apart: 10,
        roam: 7,
        odds: 0.5,
      },
      { near: 'crystals', count: 2, within: 20, apart: 10, roam: 7, odds: 0.5 },
    ],
    look: {
      plan: 'wisp',
      core: 0xffffe0,
      glow: 0xb8e050,
      mote: 0xf0ffb0,
      scale: 0.8,
    },
  },
  shardling: {
    name: 'Shardling',
    lvl: 12,
    hp: 576,
    dmg: 28,
    speed: 3.6,
    xp: 263,
    reach: 1.8,
    aggro: 8,
    respawn: 50,
    loot: [['shard', 0.8], ['gem', 0.05], ['coin', 0.5]],
    size: 1.2,
    dust: 0x9ad8f8,
    haunts: [
      { near: 'crystals', count: 3, within: 20, apart: 6, roam: 5 },
    ],
    look: {
      plan: 'crawler',
      shell: 0x7ad0f0,
      under: 0x3a6a8a,
      leg: 0x4a8ab0,
      eye: 0xffffff,
      pairs: 4,
      claws: 0x9ae0ff,
      mark: 0xc0f0ff,
      scale: 1.5,
    },
  },
  glimmerback: {
    name: 'Glimmerback',
    lvl: 10,
    hp: 440,
    dmg: 24,
    speed: 2.4,
    xp: 206,
    reach: 2,
    aggro: 5,
    respawn: 40,
    loot: [['shard', 0.8], ['coin', 0.6]],
    size: 1.5,
    dust: 0x9ad4ff,
    haunts: [
      { near: 'crystals', count: 1, within: 18, apart: 8, roam: 5 },
    ],
    look: {
      plan: 'crag',
      stone: 0x7a8490,
      light: 0x94a0ac,
      moss: 0x5a8a9a,
      eye: 0xb0f0ff,
      crystals: 0x6fc0f0,
    },
  },
  hollowking: {
    name: 'The Hollow King',
    lvl: 16,
    hp: 3140,
    dmg: 43,
    speed: 2.2,
    xp: 1540,
    reach: 3.4,
    aggro: 8,
    respawn: 300,
    loot: [['gem', 1], ['ore', 1], ['elixir', 1], ['blade5', 0.3]],
    size: 3,
    dust: 0x6a8ab8,
    haunts: [
      { near: 'crystals', count: 1, within: 16, apart: 1, roam: 4, odds: 0.65 },
    ],
    look: {
      plan: 'biped',
      skin: 0x5a6a80,
      garb: 0x4a5468,
      eye: 0x9af0ff,
      head: 'horns',
      top: 0x8ad8f0,
      build: [1.8, 1.3],
      long: true,
      stoop: 0.1,
      scale: 2,
    },
    boss: true,
  },
}
