// The creatures of the far north, on the snowfields and the ice: snow hares
// and mammoths, frost slimes and frost wolves, walking ice, and the two great
// foes of the white peaks, Frostmaw and the Skyreaver.
import type { Beast } from '../beasts.ts'

export let FROST: Record<string, Beast> = {
  snowhare: {
    name: 'Snow hare',
    lvl: 9,
    hp: 298,
    dmg: 13,
    speed: 5,
    xp: 152,
    reach: 1,
    aggro: 0,
    respawn: 25,
    loot: [['hide', 0.6], ['frost', 0.2]],
    size: 0.6,
    dust: 0xf4f6f8,
    haunts: [
      { near: 'snowfield', count: 4, within: 28, apart: 6, roam: 6 },
      { near: 'glacier', count: 4, within: 22, apart: 6, roam: 6, odds: 0.7 },
    ],
    look: {
      plan: 'hopper',
      fur: 0xf4f6f8,
      belly: 0xffffff,
      eye: 0x1a1a1a,
      ears: 'long',
      tail: 'puff',
      scale: 1.3,
    },
  },
  frostslime: {
    name: 'Frost slime',
    lvl: 10,
    hp: 440,
    dmg: 24,
    speed: 2.2,
    xp: 206,
    reach: 1.4,
    aggro: 5,
    respawn: 40,
    loot: [['frost', 0.6], ['jelly', 0.3]],
    size: 1.1,
    dust: 0xc8ecff,
    haunts: [
      { near: 'snowfield', count: 4, within: 26, apart: 7, roam: 4, odds: 0.8 },
      { near: 'glacier', count: 4, within: 22, apart: 7, roam: 4, odds: 0.8 },
    ],
    look: {
      plan: 'slime',
      body: 0x9ad8f0,
      moss: 0xf0f8ff,
      bloom: 0xffffff,
      scale: 1.2,
    },
  },
  frostback: {
    name: 'Frostback',
    lvl: 12,
    hp: 576,
    dmg: 28,
    speed: 2.2,
    xp: 263,
    reach: 2,
    aggro: 6,
    respawn: 50,
    loot: [['frost', 0.7], ['shard', 0.4], ['coin', 0.8]],
    size: 1.6,
    dust: 0xd8ecf8,
    haunts: [
      { near: 'glacier', count: 2, within: 20, apart: 8, roam: 4, odds: 0.9 },
      { near: 'snowfield', count: 2, within: 24, apart: 8, roam: 4, odds: 0.8 },
    ],
    look: {
      plan: 'crag',
      stone: 0x8a9aa8,
      light: 0xd8e8f0,
      moss: 0xf0f8ff,
      eye: 0x6ad0ff,
      crystals: 0xa8e0ff,
      scale: 1.1,
    },
  },
  frostwolf: {
    name: 'Frost wolf',
    lvl: 13,
    hp: 650,
    dmg: 31,
    speed: 5.2,
    xp: 292,
    reach: 1.8,
    aggro: 11,
    respawn: 50,
    loot: [['fang', 0.6], ['pelt', 0.6], ['frost', 0.2], ['coin', 0.5]],
    size: 1.2,
    dust: 0xe8f0f4,
    haunts: [
      { near: 'snowfield', count: 4, within: 26, apart: 6, roam: 7, odds: 0.8 },
      { near: 'glacier', count: 4, within: 22, apart: 6, roam: 7, odds: 0.7 },
      { near: 'pinewood', count: 4, within: 24, apart: 6, roam: 7, odds: 0.8 },
    ],
    look: {
      plan: 'quadruped',
      hide: 0xe8eef2,
      ridge: 0xc0ccd8,
      snout: 0xf8fbfd,
      eye: 0x6ad0ff,
      ears: 'point',
      tail: 'bush',
      belly: 0xf8fbfd,
      legs: 1.25,
      build: [0.85, 0.9, 1.15],
      muzzle: 2,
      scale: 1.2,
    },
  },
  mammoth: {
    name: 'Woolly mammoth',
    lvl: 14,
    hp: 1100,
    dmg: 38,
    speed: 3,
    xp: 400,
    reach: 2.8,
    aggro: 0,
    respawn: 90,
    loot: [['pelt', 1], ['ivory', 0.8], ['draught', 0.3]],
    size: 2.4,
    dust: 0x6a4a34,
    haunts: [
      {
        near: 'snowfield',
        count: 2,
        within: 24,
        apart: 12,
        roam: 8,
        odds: 0.7,
      },
    ],
    look: {
      plan: 'quadruped',
      hide: 0x6a4a34,
      ridge: 0x5a3a26,
      snout: 0x6a4a34,
      eye: 0x1a1010,
      tusk: 0xf4ecd8,
      ears: 'round',
      tail: 'thin',
      belly: 0x5a3a26,
      legs: 1.3,
      build: [1.5, 1.5, 1.35],
      muzzle: 1.5,
      scale: 1.45,
    },
  },
  frostmaw: {
    name: 'Frostmaw',
    lvl: 16,
    hp: 3140,
    dmg: 43,
    speed: 3,
    xp: 1540,
    reach: 3,
    aggro: 9,
    respawn: 300,
    loot: [['frost', 1], ['pelt', 1], ['elixir', 1], ['blade5', 0.25]],
    size: 2.8,
    dust: 0xe8f0f8,
    haunts: [
      {
        near: 'glacier',
        count: 1,
        beyond: 3,
        within: 12,
        apart: 1,
        roam: 5,
        odds: 0.25,
      },
      { near: 'snowfield', count: 1, within: 14, apart: 1, roam: 5, odds: 0.2 },
    ],
    look: {
      plan: 'biped',
      skin: 0x9ab0c8,
      garb: 0xe8eef4,
      eye: 0x3ad0ff,
      head: 'horns',
      top: 0x8a9aaa,
      build: [1.6, 1.25],
      long: true,
      stoop: 0.25,
      scale: 1.9,
    },
    boss: true,
  },
  skyreaver: {
    name: 'The Skyreaver',
    lvl: 18,
    hp: 3780,
    dmg: 48,
    speed: 4.4,
    xp: 1800,
    reach: 3.2,
    aggro: 10,
    respawn: 300,
    loot: [['plume', 1], ['talon', 1], ['elixir', 1], ['blade5', 0.3]],
    size: 3,
    dust: 0x4a4a6a,
    haunts: [
      {
        near: 'glacier',
        count: 1,
        beyond: 4,
        within: 10,
        apart: 1,
        roam: 8,
        odds: 0.15,
      },
      { near: 'mesa', count: 1, within: 10, apart: 1, roam: 8, odds: 0.12 },
    ],
    look: {
      plan: 'bird',
      feather: 0x3a3a52,
      wing: 0x2a2a3e,
      beak: 0xe8c040,
      eye: 0xff4030,
      belly: 0x5a5a78,
      crest: 0xd83a3a,
      bill: 'hook',
      tail: 'fan',
      fly: 1.6,
      span: 1.8,
      scale: 3.4,
    },
    boss: true,
  },
  yeti: {
    name: 'Yeti',
    lvl: 16,
    hp: 1792,
    dmg: 46,
    speed: 3.6,
    xp: 847,
    reach: 2.4,
    aggro: 9,
    respawn: 90,
    loot: [['pelt', 1], ['frost', 0.5], ['fang', 0.3], ['draught', 0.2]],
    size: 1.8,
    dust: 0xe8eef2,
    haunts: [
      {
        near: 'snowfield',
        count: 2,
        within: 24,
        apart: 14,
        roam: 6,
        odds: 0.9,
      },
      { near: 'glacier', count: 2, within: 20, apart: 14, roam: 6, odds: 0.9 },
    ],
    look: {
      plan: 'biped',
      skin: 0x9ab0c0,
      garb: 0xeef4f8,
      eye: 0x3a7ab8,
      build: [1.5, 1.45],
      head: 'horns',
      top: 0xc8d0d8,
      long: true,
      stoop: 0.2,
    },
  },
}
