// The creatures of the waters, on the banks of every lake, marsh, coast and
// oasis: frogs, ducks and herons, crabs and seals on the shore, otters and
// beavers, and in the reeds the mire troll and Old Mudjaw, the toad as big as
// a cart.
import type { Beast } from '../beasts.ts'

export let WATERS: Record<string, Beast> = {
  frog: {
    name: 'Mere frog',
    lvl: 1,
    hp: 22,
    dmg: 3,
    speed: 2.4,
    xp: 12,
    reach: 1,
    aggro: 0,
    respawn: 16,
    loot: [['toadstone', 0.04], ['coin', 0.2]],
    size: 0.45,
    dust: 0x5aa04a,
    haunts: [
      { near: 'lake', count: 3, beyond: 9, within: 22, apart: 5, roam: 4 },
      { near: 'marsh', count: 3, within: 28, apart: 5, roam: 4 },
    ],
    look: {
      plan: 'hopper',
      fur: 0x5aa04a,
      belly: 0xe0e8a0,
      eye: 0x1a1a10,
      frog: true,
    },
  },
  duck: {
    name: 'Mallard',
    lvl: 1,
    hp: 20,
    dmg: 2,
    speed: 2.8,
    xp: 11,
    reach: 1,
    aggro: 0,
    respawn: 16,
    loot: [['feather', 0.7], ['egg', 0.3]],
    size: 0.55,
    dust: 0x8a7a5a,
    haunts: [
      { near: 'lake', count: 2, beyond: 10, within: 22, apart: 5, roam: 5 },
    ],
    look: {
      plan: 'bird',
      feather: 0x8a7258,
      wing: 0x6a5a48,
      beak: 0xe8c040,
      eye: 0x1a1a1a,
      belly: 0xb8a488,
      bill: 'flat',
      neck: 1.2,
      legs: 0.7,
      scale: 1.1,
    },
  },
  heron: {
    name: 'Grey heron',
    lvl: 3,
    hp: 70,
    dmg: 8,
    speed: 3.6,
    xp: 42,
    reach: 1.6,
    aggro: 0,
    respawn: 25,
    loot: [['feather', 0.8], ['quill', 0.2]],
    size: 0.9,
    dust: 0xb8bcc0,
    haunts: [
      {
        near: 'lake',
        count: 1,
        beyond: 10,
        within: 20,
        apart: 8,
        roam: 5,
        odds: 0.7,
      },
      { near: 'marsh', count: 1, within: 26, apart: 8, roam: 5, odds: 0.6 },
    ],
    look: {
      plan: 'bird',
      feather: 0xb8bcc4,
      wing: 0x8a8e98,
      beak: 0xe0c050,
      eye: 0xf0d040,
      crest: 0x2a2a30,
      bill: 'long',
      neck: 3.5,
      legs: 3,
      scale: 1.3,
    },
  },
  swan: {
    name: 'Mute swan',
    lvl: 6,
    hp: 216,
    dmg: 15,
    speed: 3.4,
    xp: 105,
    reach: 1.5,
    aggro: 6,
    respawn: 30,
    loot: [['feather', 0.8], ['plume', 0.04]],
    size: 1,
    dust: 0xf4f4f0,
    haunts: [
      {
        near: 'lake',
        count: 1,
        beyond: 11,
        within: 20,
        apart: 9,
        roam: 5,
        odds: 0.5,
      },
    ],
    look: {
      plan: 'bird',
      feather: 0xf6f6f0,
      wing: 0xeaeae4,
      beak: 0xe86a2a,
      eye: 0x1a1a1a,
      bill: 'flat',
      neck: 3,
      legs: 0.8,
      scale: 1.6,
    },
  },
  crab: {
    name: 'Shore crab',
    lvl: 5,
    hp: 170,
    dmg: 12,
    speed: 2.6,
    xp: 84,
    reach: 1.2,
    aggro: 5,
    respawn: 20,
    loot: [['shell', 0.6], ['coin', 0.2]],
    size: 0.6,
    dust: 0xc8603a,
    haunts: [
      { near: 'coast', count: 3, within: 22, apart: 5, roam: 4, odds: 0.8 },
    ],
    look: {
      plan: 'crawler',
      shell: 0xc8603a,
      under: 0xe8c8a0,
      leg: 0xb8502e,
      eye: 0x1a1010,
      claws: 0xd86a40,
      scale: 1.1,
    },
  },
  snapclaw: {
    name: 'Snapclaw',
    lvl: 10,
    hp: 629,
    dmg: 26,
    speed: 2.6,
    xp: 239,
    reach: 2,
    aggro: 7,
    respawn: 45,
    loot: [['shell', 0.8], ['pearl', 0.15], ['coin', 0.6]],
    size: 1.4,
    dust: 0x8a3a5a,
    haunts: [
      { near: 'coast', count: 2, within: 20, apart: 10, roam: 5, odds: 0.7 },
      { near: 'isles', count: 2, within: 24, apart: 10, roam: 5, odds: 0.7 },
    ],
    look: {
      plan: 'crawler',
      shell: 0x7a3a58,
      under: 0xd8b8b0,
      leg: 0x6a2e48,
      eye: 0xffd040,
      claws: 0x9a4a6a,
      mark: 0xb86a8a,
      scale: 2.4,
    },
  },
  turtle: {
    name: 'Mossback turtle',
    lvl: 4,
    hp: 190,
    dmg: 9,
    speed: 1.4,
    xp: 63,
    reach: 1.3,
    aggro: 0,
    respawn: 30,
    loot: [['shell', 0.8], ['coin', 0.2]],
    size: 0.9,
    dust: 0x5a7a3a,
    haunts: [
      {
        near: 'lake',
        count: 1,
        beyond: 9,
        within: 20,
        apart: 8,
        roam: 3,
        odds: 0.5,
      },
      { near: 'coast', count: 2, within: 22, apart: 8, roam: 3, odds: 0.5 },
    ],
    look: {
      plan: 'crawler',
      shell: 0x4a6a34,
      under: 0xc8b888,
      leg: 0x7a8a5a,
      eye: 0x1a1a10,
      dome: true,
      pairs: 2,
      mark: 0x6a9a48,
      scale: 1.3,
    },
  },
  otter: {
    name: 'River otter',
    lvl: 2,
    hp: 50,
    dmg: 5,
    speed: 4.2,
    xp: 26,
    reach: 1.2,
    aggro: 0,
    respawn: 20,
    loot: [['pelt', 0.6]],
    size: 0.6,
    dust: 0x6a4a30,
    haunts: [
      {
        near: 'lake',
        count: 1,
        beyond: 10,
        within: 20,
        apart: 7,
        roam: 6,
        odds: 0.6,
      },
    ],
    look: {
      plan: 'quadruped',
      hide: 0x6a4a30,
      ridge: 0x5a3a24,
      snout: 0xc8b098,
      eye: 0x1a1010,
      belly: 0xc8b098,
      ears: 'round',
      tail: 'thin',
      legs: 0.55,
      build: [0.7, 0.7, 1.35],
      muzzle: 1.2,
      scale: 0.7,
    },
  },
  beaver: {
    name: 'Dam beaver',
    lvl: 3,
    hp: 90,
    dmg: 7,
    speed: 2.6,
    xp: 42,
    reach: 1.2,
    aggro: 0,
    respawn: 24,
    loot: [['pelt', 0.5], ['bark', 0.4]],
    size: 0.7,
    dust: 0x7a5232,
    haunts: [
      {
        near: 'lake',
        count: 1,
        beyond: 10,
        within: 22,
        apart: 8,
        roam: 4,
        odds: 0.5,
      },
    ],
    look: {
      plan: 'quadruped',
      hide: 0x7a5232,
      ridge: 0x5a3a22,
      snout: 0x8a6a4a,
      eye: 0x1a1010,
      tusk: 0xf0a040,
      ears: 'round',
      tail: 'flat',
      legs: 0.55,
      build: [1, 0.9, 0.9],
      scale: 0.75,
    },
  },
  watersnake: {
    name: 'Water snake',
    lvl: 6,
    hp: 202,
    dmg: 16,
    speed: 3,
    xp: 107,
    reach: 1.4,
    aggro: 5,
    respawn: 24,
    loot: [['scale', 0.6], ['coin', 0.2]],
    size: 0.8,
    dust: 0x3a5a6a,
    haunts: [
      {
        near: 'lake',
        count: 1,
        beyond: 9,
        within: 20,
        apart: 7,
        roam: 5,
        odds: 0.6,
      },
      { near: 'marsh', count: 2, within: 26, apart: 7, roam: 5, odds: 0.6 },
    ],
    look: {
      plan: 'serpent',
      skin: 0x3a5a6a,
      belly: 0xc8c8a8,
      eye: 0xe0c040,
      band: 0x2a3a44,
      length: 7,
      scale: 1.1,
    },
  },
  bogslime: {
    name: 'Bog slime',
    lvl: 5,
    hp: 181,
    dmg: 14,
    speed: 2,
    xp: 85,
    reach: 1.3,
    aggro: 4,
    respawn: 25,
    loot: [['jelly', 0.7], ['spore', 0.3]],
    size: 1,
    dust: 0x6a6a3a,
    haunts: [
      {
        near: 'lake',
        count: 1,
        beyond: 10,
        within: 22,
        apart: 7,
        roam: 4,
        odds: 0.5,
      },
      { near: 'marsh', count: 2, within: 28, apart: 7, roam: 4, odds: 0.7 },
      {
        near: 'shroomwood',
        count: 1,
        within: 24,
        apart: 7,
        roam: 4,
        odds: 0.4,
      },
    ],
    look: {
      plan: 'slime',
      body: 0x6a6a3a,
      moss: 0x4a5a2a,
      bloom: 0xc8a8e0,
      scale: 1.1,
    },
  },
  darter: {
    name: 'Blue darter',
    lvl: 2,
    hp: 36,
    dmg: 5,
    speed: 4.4,
    xp: 24,
    reach: 1.2,
    aggro: 0,
    respawn: 18,
    loot: [['dust', 0.5], ['glow', 0.05]],
    size: 0.6,
    dust: 0x3a8ad8,
    haunts: [
      {
        near: 'lake',
        count: 2,
        beyond: 8,
        within: 20,
        apart: 6,
        roam: 7,
        odds: 0.6,
      },
      { near: 'marsh', count: 2, within: 26, apart: 6, roam: 7, odds: 0.6 },
    ],
    look: {
      plan: 'flier',
      body: 0x3a8ad8,
      wing: 0xe0f0f8,
      eye: 0x1a3a5a,
      wings: 'clear',
      long: true,
      stripe: 0x1a4a7a,
      fly: 1.2,
      scale: 1.3,
    },
  },
  lantern: {
    name: 'Mire lantern',
    lvl: 8,
    hp: 296,
    dmg: 21,
    speed: 3,
    xp: 154,
    reach: 1.5,
    aggro: 8,
    respawn: 40,
    loot: [['glow', 0.7], ['coin', 0.4]],
    size: 0.8,
    dust: 0xa0f0c0,
    haunts: [
      {
        near: 'lake',
        count: 2,
        beyond: 8,
        within: 18,
        apart: 10,
        roam: 7,
        odds: 0.5,
      },
      { near: 'marsh', count: 2, within: 26, apart: 10, roam: 7, odds: 0.8 },
    ],
    look: {
      plan: 'wisp',
      core: 0xf0fff0,
      glow: 0x6ae0a0,
      mote: 0xc0ffd8,
      fly: 0.8,
    },
  },
  troll: {
    name: 'Mire troll',
    lvl: 11,
    hp: 1017,
    dmg: 34,
    speed: 3,
    xp: 516,
    reach: 2.4,
    aggro: 7,
    respawn: 90,
    loot: [['bone', 0.6], ['coin', 1], ['draught', 0.3], ['blade4', 0.05]],
    size: 2,
    dust: 0x4a5a44,
    haunts: [
      { near: 'marsh', count: 2, within: 24, apart: 10, roam: 5, odds: 0.7 },
    ],
    look: {
      plan: 'biped',
      skin: 0x5a7064,
      garb: 0x5a6a3a,
      eye: 0xffc040,
      head: 'snout',
      top: 0x8a8070,
      club: 0x5a4632,
      build: [1.5, 1.35],
      long: true,
      stoop: 0.3,
      scale: 1.4,
    },
  },
  mudjaw: {
    name: 'Old Mudjaw',
    lvl: 13,
    hp: 2275,
    dmg: 36,
    speed: 2.4,
    xp: 1160,
    reach: 3,
    aggro: 6,
    respawn: 200,
    loot: [['toadstone', 1], ['pearl', 0.5], ['draught', 1], ['coin', 1]],
    size: 2.6,
    dust: 0x5a5a32,
    haunts: [
      { near: 'marsh', count: 1, within: 14, apart: 1, roam: 4, odds: 0.4 },
    ],
    look: {
      plan: 'hopper',
      fur: 0x5e5c32,
      belly: 0xc8c090,
      eye: 0xff8a2a,
      frog: true,
      scale: 4.2,
    },
    boss: true,
  },
  gull: {
    name: 'Harbour gull',
    lvl: 5,
    hp: 132,
    dmg: 12,
    speed: 4.4,
    xp: 79,
    reach: 1.2,
    aggro: 4,
    respawn: 24,
    loot: [['feather', 0.8], ['coin', 0.3], ['egg', 0.2]],
    size: 0.7,
    dust: 0xf0f0ec,
    haunts: [
      { near: 'coast', count: 3, within: 24, apart: 6, roam: 8, odds: 0.8 },
    ],
    look: {
      plan: 'bird',
      feather: 0xf4f4f0,
      wing: 0xa8b0b8,
      beak: 0xf0c040,
      eye: 0x1a1a1a,
      fly: 1.8,
      span: 1.4,
      scale: 1.2,
    },
  },
  seal: {
    name: 'Grey seal',
    lvl: 7,
    hp: 332,
    dmg: 14,
    speed: 2.2,
    xp: 122,
    reach: 1.4,
    aggro: 0,
    respawn: 30,
    loot: [['pelt', 0.6], ['pearl', 0.05]],
    size: 1,
    dust: 0x7a8088,
    haunts: [
      { near: 'coast', count: 2, within: 22, apart: 8, roam: 4, odds: 0.7 },
      { near: 'isles', count: 2, within: 26, apart: 8, roam: 4, odds: 0.8 },
    ],
    look: {
      plan: 'quadruped',
      hide: 0x7a8088,
      ridge: 0x5a6068,
      snout: 0xa8b0b8,
      eye: 0x101010,
      belly: 0xb8c0c8,
      tail: 'flat',
      legs: 0.3,
      build: [1, 0.9, 1.4],
      muzzle: 1.1,
      scale: 0.9,
    },
  },
  seaserpent: {
    name: 'Sea serpent',
    lvl: 12,
    hp: 576,
    dmg: 28,
    speed: 3.8,
    xp: 263,
    reach: 2.4,
    aggro: 8,
    respawn: 60,
    loot: [['scale', 0.8], ['fang', 0.3], ['pearl', 0.2]],
    size: 1.8,
    dust: 0x2a6a7a,
    haunts: [
      { near: 'coast', count: 2, within: 24, apart: 12, roam: 6, odds: 0.9 },
      { near: 'isles', count: 4, within: 26, apart: 12, roam: 6 },
    ],
    look: {
      plan: 'serpent',
      skin: 0x2a6a7a,
      belly: 0x9ad0c8,
      eye: 0xffe040,
      band: 0x1a4a58,
      frill: 0x4ab0a0,
      length: 10,
      girth: 2.2,
      scale: 1.2,
    },
  },
}
