// Generating an eid, and telling a generated one from a name somebody chose.
//
// Clients and servers both generate eids — a client assigns the id of the
// entity it is creating, so a write takes one round trip and never waits for an
// id. That is why the id is built from plain `getRandomValues`:
// `crypto.randomUUID` is only available in secure contexts, and a page served
// over plain HTTP still has to generate ids.

/**
 * A fresh eid: a random (v4) UUID. Works anywhere `crypto.getRandomValues`
 * does — a browser on plain HTTP, a worker, a server.
 */
export let mint = (): string => {
  let b = crypto.getRandomValues(new Uint8Array(16))
  b[6] = (b[6] & 0x0f) | 0x40 // version 4
  b[8] = (b[8] & 0x3f) | 0x80 // variant 1
  let h = [...b].map((x) => x.toString(16).padStart(2, '0')).join('')
  return `${h.slice(0, 8)}-${h.slice(8, 12)}-${h.slice(12, 16)}-${
    h.slice(16, 20)
  }-${h.slice(20)}`
}

// What a generated id looks like: a UUID, or the hex of a content address
// (./identity.ts `derivedEid`, a key, a blob). A string of that shape is a
// generated id whatever the caller intended, so every lookup that means "an
// eid, otherwise a name somebody chose" tells the two apart here rather than
// each having its own copy of the test.
let MINTED = /^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$|^[0-9a-f]{40,64}$/i

/**
 * Whether an id was generated by these packages, rather than chosen by a
 * person.
 *
 * ```ts
 * minted(mint()) // true
 * minted('lemon-cake') // false
 * ```
 */
export let minted = (id: string): boolean => MINTED.test(id)
